<?php


/**
 * This class adds structure of 'tb012_tipo_cuenta_bancaria' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Jan  7 13:26:52 2022
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Tb012TipoCuentaBancariaMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Tb012TipoCuentaBancariaMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Tb012TipoCuentaBancariaPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Tb012TipoCuentaBancariaPeer::TABLE_NAME);
		$tMap->setPhpName('Tb012TipoCuentaBancaria');
		$tMap->setClassname('Tb012TipoCuentaBancaria');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('tb012_tipo_cuenta_bancaria_co_tipo_cuenta_seq');

		$tMap->addPrimaryKey('CO_TIPO_CUENTA', 'CoTipoCuenta', 'BIGINT', true, null);

		$tMap->addColumn('TX_TIPO_CUENTA', 'TxTipoCuenta', 'VARCHAR', false, 255);

		$tMap->addColumn('CO_EMPRESA', 'CoEmpresa', 'BIGINT', false, null);

	} // doBuild()

} // Tb012TipoCuentaBancariaMapBuilder
