<?php


/**
 * This class adds structure of 'tb019_programa' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun  6 08:13:27 2022
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Tb019ProgramaMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Tb019ProgramaMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Tb019ProgramaPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Tb019ProgramaPeer::TABLE_NAME);
		$tMap->setPhpName('Tb019Programa');
		$tMap->setClassname('Tb019Programa');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('tb019_programa_co_programa_seq');

		$tMap->addPrimaryKey('CO_PROGRAMA', 'CoPrograma', 'BIGINT', true, null);

		$tMap->addForeignKey('CO_SECTOR', 'CoSector', 'BIGINT', 'tb018_sector', 'CO_SECTOR', false, null);

		$tMap->addColumn('NU_PROGRAMA', 'NuPrograma', 'VARCHAR', false, 255);

		$tMap->addColumn('TX_DENOMINACION', 'TxDenominacion', 'VARCHAR', false, 255);

	} // doBuild()

} // Tb019ProgramaMapBuilder
