<?php


/**
 * This class adds structure of 'tb069_fondo_tercero' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Jan  7 13:26:53 2022
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Tb069FondoTerceroMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Tb069FondoTerceroMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Tb069FondoTerceroPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Tb069FondoTerceroPeer::TABLE_NAME);
		$tMap->setPhpName('Tb069FondoTercero');
		$tMap->setClassname('Tb069FondoTercero');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('tb069_fondo_tercero_co_fondo_tercero_seq');

		$tMap->addPrimaryKey('CO_FONDO_TERCERO', 'CoFondoTercero', 'BIGINT', true, null);

		$tMap->addColumn('CO_SOLICITUD', 'CoSolicitud', 'BIGINT', false, null);

		$tMap->addColumn('CO_PROVEEDOR', 'CoProveedor', 'BIGINT', false, null);

		$tMap->addColumn('FE_EMISION', 'FeEmision', 'DATE', false, null);

		$tMap->addColumn('NU_DECLARACION', 'NuDeclaracion', 'VARCHAR', false, 255);

		$tMap->addColumn('TX_OBSERVACION', 'TxObservacion', 'VARCHAR', false, 255);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('CO_USUARIO', 'CoUsuario', 'BIGINT', false, null);

		$tMap->addColumn('MO_PAGAR', 'MoPagar', 'NUMERIC', false, null);

		$tMap->addColumn('CO_SOLICITUD_ANULAR', 'CoSolicitudAnular', 'BIGINT', false, null);

		$tMap->addColumn('IN_ANULAR', 'InAnular', 'BOOLEAN', false, null);

	} // doBuild()

} // Tb069FondoTerceroMapBuilder
