<?php


/**
 * This class adds structure of 'tb133_tipo_asiento' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun  6 08:13:31 2022
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Tb133TipoAsientoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Tb133TipoAsientoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Tb133TipoAsientoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Tb133TipoAsientoPeer::TABLE_NAME);
		$tMap->setPhpName('Tb133TipoAsiento');
		$tMap->setClassname('Tb133TipoAsiento');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('tb133_tipo_asiento_co_tipo_asiento_seq');

		$tMap->addPrimaryKey('CO_TIPO_ASIENTO', 'CoTipoAsiento', 'BIGINT', true, null);

		$tMap->addColumn('TX_TIPO_ASIENTO', 'TxTipoAsiento', 'VARCHAR', false, 255);

	} // doBuild()

} // Tb133TipoAsientoMapBuilder
