<?php


/**
 * This class adds structure of 'tbbn016_reporte' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun  6 08:13:34 2022
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Tbbn016ReporteMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Tbbn016ReporteMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Tbbn016ReportePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Tbbn016ReportePeer::TABLE_NAME);
		$tMap->setPhpName('Tbbn016Reporte');
		$tMap->setClassname('Tbbn016Reporte');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('tbbn016_reporte_co_reporte_seq');

		$tMap->addPrimaryKey('CO_REPORTE', 'CoReporte', 'BIGINT', true, null);

		$tMap->addColumn('CO_TIPO_REPORTE', 'CoTipoReporte', 'BIGINT', false, null);

		$tMap->addForeignKey('CO_SOLICITUD', 'CoSolicitud', 'BIGINT', 'tb026_solicitud', 'CO_SOLICITUD', false, null);

		$tMap->addForeignKey('CO_USUARIO', 'CoUsuario', 'BIGINT', 'tb001_usuario', 'CO_USUARIO', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // Tbbn016ReporteMapBuilder
