<?php


/**
 * This class adds structure of 'tbrh079_remuneracion_obreros' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Jan  7 13:26:54 2022
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Tbrh079RemuneracionObrerosMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Tbrh079RemuneracionObrerosMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Tbrh079RemuneracionObrerosPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Tbrh079RemuneracionObrerosPeer::TABLE_NAME);
		$tMap->setPhpName('Tbrh079RemuneracionObreros');
		$tMap->setClassname('Tbrh079RemuneracionObreros');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('tbrh079_remuneracion_obreros_co_remuneraciones_obreros_seq');

		$tMap->addColumn('CO_REMUNERACIONES_OBREROS', 'CoRemuneracionesObreros', 'BIGINT', true, null);

		$tMap->addColumn('NU_GRADO', 'NuGrado', 'NUMERIC', false, null);

		$tMap->addColumn('MO_SALARIO', 'MoSalario', 'NUMERIC', false, 32);

		$tMap->addColumn('CO_TP_FUNCIONARIO', 'CoTpFuncionario', 'BIGINT', false, null);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

	} // doBuild()

} // Tbrh079RemuneracionObrerosMapBuilder
