<?php


/**
 * This class adds structure of 'tbrh061_nomina_movimiento' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Jan  7 13:26:54 2022
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Tbrh061NominaMovimientoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Tbrh061NominaMovimientoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(Tbrh061NominaMovimientoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(Tbrh061NominaMovimientoPeer::TABLE_NAME);
		$tMap->setPhpName('Tbrh061NominaMovimiento');
		$tMap->setClassname('Tbrh061NominaMovimiento');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('tbrh061_nomina_movimiento_id_seq');

		$tMap->addPrimaryKey('ID', 'Id', 'BIGINT', true, null);

		$tMap->addColumn('ID_TBRH013_NOMINA', 'IdTbrh013Nomina', 'BIGINT', true, null);

		$tMap->addColumn('ID_TBRH014_CONCEPTO', 'IdTbrh014Concepto', 'BIGINT', true, null);

		$tMap->addColumn('ID_TBRH020_TP_CONCEPTO', 'IdTbrh020TpConcepto', 'BIGINT', false, null);

		$tMap->addColumn('ID_TBRH002_FICHA', 'IdTbrh002Ficha', 'BIGINT', true, null);

		$tMap->addColumn('DE_CONCEPTO', 'DeConcepto', 'VARCHAR', true, 255);

		$tMap->addColumn('NU_VALOR', 'NuValor', 'NUMERIC', false, 32);

		$tMap->addColumn('NU_MONTO', 'NuMonto', 'NUMERIC', true, 32);

		$tMap->addColumn('ID_TBRH050_TP_UNIDAD', 'IdTbrh050TpUnidad', 'BIGINT', true, null);

		$tMap->addColumn('IN_ACTIVO', 'InActivo', 'BOOLEAN', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', true, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', true, null);

		$tMap->addColumn('IN_IMPRIME_DETALLE', 'InImprimeDetalle', 'BOOLEAN', false, null);

		$tMap->addColumn('IN_DESCRIPCION_ALTERNATIVA', 'InDescripcionAlternativa', 'BOOLEAN', false, null);

		$tMap->addColumn('IN_VALOR_REFERENCIA', 'InValorReferencia', 'BOOLEAN', false, null);

		$tMap->addColumn('IN_HOJA_TIEMPO', 'InHojaTiempo', 'BOOLEAN', false, null);

		$tMap->addColumn('IN_PRORRATEA', 'InProrratea', 'BOOLEAN', false, null);

		$tMap->addColumn('IN_MODIFICA_DESCRIPCION', 'InModificaDescripcion', 'BOOLEAN', false, null);

		$tMap->addColumn('IN_MONTO_CALCULO', 'InMontoCalculo', 'BOOLEAN', false, null);

		$tMap->addColumn('IN_CONTRACTUAL', 'InContractual', 'BOOLEAN', false, null);

		$tMap->addColumn('IN_BONIFICABLE', 'InBonificable', 'BOOLEAN', false, null);

		$tMap->addColumn('IN_MONTO_CERO', 'InMontoCero', 'BOOLEAN', false, null);

		$tMap->addColumn('ID_TBRH030_MONEDA', 'IdTbrh030Moneda', 'BIGINT', true, null);

		$tMap->addColumn('ID_TBRH015_NOM_TRABAJADOR', 'IdTbrh015NomTrabajador', 'BIGINT', false, null);

		$tMap->addColumn('ID_TBRH086_CONCEPTOS_FIJOS', 'IdTbrh086ConceptosFijos', 'BIGINT', false, null);

		$tMap->addColumn('NU_PRIORIDAD', 'NuPrioridad', 'BIGINT', false, null);

	} // doBuild()

} // Tbrh061NominaMovimientoMapBuilder
