<?php

/**
 * Base class that represents a row from the 'tb034_revision' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun  6 08:13:28 2022
 *
 * @package    lib.model.om
 */
abstract class BaseTb034Revision extends BaseObject  implements Persistent {


  const PEER = 'Tb034RevisionPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        Tb034RevisionPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_revision field.
	 * @var        string
	 */
	protected $co_revision;

	/**
	 * The value for the co_usuario_envia field.
	 * @var        string
	 */
	protected $co_usuario_envia;

	/**
	 * The value for the tx_comentario field.
	 * @var        string
	 */
	protected $tx_comentario;

	/**
	 * The value for the fe_envio field.
	 * @var        string
	 */
	protected $fe_envio;

	/**
	 * The value for the co_usuario_resp field.
	 * @var        string
	 */
	protected $co_usuario_resp;

	/**
	 * The value for the tx_respuesta field.
	 * @var        string
	 */
	protected $tx_respuesta;

	/**
	 * The value for the fe_respuesta field.
	 * @var        string
	 */
	protected $fe_respuesta;

	/**
	 * The value for the co_solicitud field.
	 * @var        string
	 */
	protected $co_solicitud;

	/**
	 * The value for the in_activo field.
	 * @var        boolean
	 */
	protected $in_activo;

	/**
	 * The value for the co_ruta field.
	 * @var        string
	 */
	protected $co_ruta;

	/**
	 * The value for the im_documento_recibido field.
	 * @var        resource
	 */
	protected $im_documento_recibido;

	/**
	 * The value for the mime_documento_recibido field.
	 * @var        string
	 */
	protected $mime_documento_recibido;

	/**
	 * The value for the im_documento_respuesta field.
	 * @var        resource
	 */
	protected $im_documento_respuesta;

	/**
	 * The value for the mime_documento_respuesta field.
	 * @var        string
	 */
	protected $mime_documento_respuesta;

	/**
	 * The value for the co_proceso field.
	 * @var        string
	 */
	protected $co_proceso;

	/**
	 * @var        Tb001Usuario
	 */
	protected $aTb001UsuarioRelatedByCoUsuarioEnvia;

	/**
	 * @var        Tb001Usuario
	 */
	protected $aTb001UsuarioRelatedByCoUsuarioResp;

	/**
	 * @var        Tb026Solicitud
	 */
	protected $aTb026Solicitud;

	/**
	 * @var        Tb030Ruta
	 */
	protected $aTb030Ruta;

	/**
	 * @var        Tb028Proceso
	 */
	protected $aTb028Proceso;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseTb034Revision object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_revision] column value.
	 * 
	 * @return     string
	 */
	public function getCoRevision()
	{
		return $this->co_revision;
	}

	/**
	 * Get the [co_usuario_envia] column value.
	 * 
	 * @return     string
	 */
	public function getCoUsuarioEnvia()
	{
		return $this->co_usuario_envia;
	}

	/**
	 * Get the [tx_comentario] column value.
	 * 
	 * @return     string
	 */
	public function getTxComentario()
	{
		return $this->tx_comentario;
	}

	/**
	 * Get the [optionally formatted] temporal [fe_envio] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFeEnvio($format = 'Y-m-d')
	{
		if ($this->fe_envio === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fe_envio);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fe_envio, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_usuario_resp] column value.
	 * 
	 * @return     string
	 */
	public function getCoUsuarioResp()
	{
		return $this->co_usuario_resp;
	}

	/**
	 * Get the [tx_respuesta] column value.
	 * 
	 * @return     string
	 */
	public function getTxRespuesta()
	{
		return $this->tx_respuesta;
	}

	/**
	 * Get the [optionally formatted] temporal [fe_respuesta] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFeRespuesta($format = 'Y-m-d')
	{
		if ($this->fe_respuesta === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fe_respuesta);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fe_respuesta, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_solicitud] column value.
	 * 
	 * @return     string
	 */
	public function getCoSolicitud()
	{
		return $this->co_solicitud;
	}

	/**
	 * Get the [in_activo] column value.
	 * 
	 * @return     boolean
	 */
	public function getInActivo()
	{
		return $this->in_activo;
	}

	/**
	 * Get the [co_ruta] column value.
	 * 
	 * @return     string
	 */
	public function getCoRuta()
	{
		return $this->co_ruta;
	}

	/**
	 * Get the [im_documento_recibido] column value.
	 * 
	 * @return     resource
	 */
	public function getImDocumentoRecibido()
	{
		return $this->im_documento_recibido;
	}

	/**
	 * Get the [mime_documento_recibido] column value.
	 * 
	 * @return     string
	 */
	public function getMimeDocumentoRecibido()
	{
		return $this->mime_documento_recibido;
	}

	/**
	 * Get the [im_documento_respuesta] column value.
	 * 
	 * @return     resource
	 */
	public function getImDocumentoRespuesta()
	{
		return $this->im_documento_respuesta;
	}

	/**
	 * Get the [mime_documento_respuesta] column value.
	 * 
	 * @return     string
	 */
	public function getMimeDocumentoRespuesta()
	{
		return $this->mime_documento_respuesta;
	}

	/**
	 * Get the [co_proceso] column value.
	 * 
	 * @return     string
	 */
	public function getCoProceso()
	{
		return $this->co_proceso;
	}

	/**
	 * Set the value of [co_revision] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setCoRevision($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_revision !== $v) {
			$this->co_revision = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::CO_REVISION;
		}

		return $this;
	} // setCoRevision()

	/**
	 * Set the value of [co_usuario_envia] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setCoUsuarioEnvia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_usuario_envia !== $v) {
			$this->co_usuario_envia = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::CO_USUARIO_ENVIA;
		}

		if ($this->aTb001UsuarioRelatedByCoUsuarioEnvia !== null && $this->aTb001UsuarioRelatedByCoUsuarioEnvia->getCoUsuario() !== $v) {
			$this->aTb001UsuarioRelatedByCoUsuarioEnvia = null;
		}

		return $this;
	} // setCoUsuarioEnvia()

	/**
	 * Set the value of [tx_comentario] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setTxComentario($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_comentario !== $v) {
			$this->tx_comentario = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::TX_COMENTARIO;
		}

		return $this;
	} // setTxComentario()

	/**
	 * Sets the value of [fe_envio] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setFeEnvio($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fe_envio !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fe_envio !== null && $tmpDt = new DateTime($this->fe_envio)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fe_envio = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = Tb034RevisionPeer::FE_ENVIO;
			}
		} // if either are not null

		return $this;
	} // setFeEnvio()

	/**
	 * Set the value of [co_usuario_resp] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setCoUsuarioResp($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_usuario_resp !== $v) {
			$this->co_usuario_resp = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::CO_USUARIO_RESP;
		}

		if ($this->aTb001UsuarioRelatedByCoUsuarioResp !== null && $this->aTb001UsuarioRelatedByCoUsuarioResp->getCoUsuario() !== $v) {
			$this->aTb001UsuarioRelatedByCoUsuarioResp = null;
		}

		return $this;
	} // setCoUsuarioResp()

	/**
	 * Set the value of [tx_respuesta] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setTxRespuesta($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_respuesta !== $v) {
			$this->tx_respuesta = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::TX_RESPUESTA;
		}

		return $this;
	} // setTxRespuesta()

	/**
	 * Sets the value of [fe_respuesta] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setFeRespuesta($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fe_respuesta !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fe_respuesta !== null && $tmpDt = new DateTime($this->fe_respuesta)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fe_respuesta = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = Tb034RevisionPeer::FE_RESPUESTA;
			}
		} // if either are not null

		return $this;
	} // setFeRespuesta()

	/**
	 * Set the value of [co_solicitud] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setCoSolicitud($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_solicitud !== $v) {
			$this->co_solicitud = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::CO_SOLICITUD;
		}

		if ($this->aTb026Solicitud !== null && $this->aTb026Solicitud->getCoSolicitud() !== $v) {
			$this->aTb026Solicitud = null;
		}

		return $this;
	} // setCoSolicitud()

	/**
	 * Set the value of [in_activo] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setInActivo($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->in_activo !== $v) {
			$this->in_activo = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::IN_ACTIVO;
		}

		return $this;
	} // setInActivo()

	/**
	 * Set the value of [co_ruta] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setCoRuta($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_ruta !== $v) {
			$this->co_ruta = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::CO_RUTA;
		}

		if ($this->aTb030Ruta !== null && $this->aTb030Ruta->getCoRuta() !== $v) {
			$this->aTb030Ruta = null;
		}

		return $this;
	} // setCoRuta()

	/**
	 * Set the value of [im_documento_recibido] column.
	 * 
	 * @param      resource $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setImDocumentoRecibido($v)
	{
		// Because BLOB columns are streams in PDO we have to assume that they are
		// always modified when a new value is passed in.  For example, the contents
		// of the stream itself may have changed externally.
		if (!is_resource($v)) {
			$this->im_documento_recibido = fopen('php://memory', 'r+');
			fwrite($this->im_documento_recibido, $v);
			rewind($this->im_documento_recibido);
		} else { // it's already a stream
			$this->im_documento_recibido = $v;
		}
		$this->modifiedColumns[] = Tb034RevisionPeer::IM_DOCUMENTO_RECIBIDO;

		return $this;
	} // setImDocumentoRecibido()

	/**
	 * Set the value of [mime_documento_recibido] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setMimeDocumentoRecibido($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mime_documento_recibido !== $v) {
			$this->mime_documento_recibido = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::MIME_DOCUMENTO_RECIBIDO;
		}

		return $this;
	} // setMimeDocumentoRecibido()

	/**
	 * Set the value of [im_documento_respuesta] column.
	 * 
	 * @param      resource $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setImDocumentoRespuesta($v)
	{
		// Because BLOB columns are streams in PDO we have to assume that they are
		// always modified when a new value is passed in.  For example, the contents
		// of the stream itself may have changed externally.
		if (!is_resource($v)) {
			$this->im_documento_respuesta = fopen('php://memory', 'r+');
			fwrite($this->im_documento_respuesta, $v);
			rewind($this->im_documento_respuesta);
		} else { // it's already a stream
			$this->im_documento_respuesta = $v;
		}
		$this->modifiedColumns[] = Tb034RevisionPeer::IM_DOCUMENTO_RESPUESTA;

		return $this;
	} // setImDocumentoRespuesta()

	/**
	 * Set the value of [mime_documento_respuesta] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setMimeDocumentoRespuesta($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mime_documento_respuesta !== $v) {
			$this->mime_documento_respuesta = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::MIME_DOCUMENTO_RESPUESTA;
		}

		return $this;
	} // setMimeDocumentoRespuesta()

	/**
	 * Set the value of [co_proceso] column.
	 * 
	 * @param      string $v new value
	 * @return     Tb034Revision The current object (for fluent API support)
	 */
	public function setCoProceso($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_proceso !== $v) {
			$this->co_proceso = $v;
			$this->modifiedColumns[] = Tb034RevisionPeer::CO_PROCESO;
		}

		if ($this->aTb028Proceso !== null && $this->aTb028Proceso->getCoProceso() !== $v) {
			$this->aTb028Proceso = null;
		}

		return $this;
	} // setCoProceso()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_revision = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->co_usuario_envia = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->tx_comentario = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->fe_envio = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->co_usuario_resp = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->tx_respuesta = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->fe_respuesta = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->co_solicitud = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->in_activo = ($row[$startcol + 8] !== null) ? (boolean) $row[$startcol + 8] : null;
			$this->co_ruta = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->im_documento_recibido = $row[$startcol + 10];
			$this->mime_documento_recibido = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->im_documento_respuesta = $row[$startcol + 12];
			$this->mime_documento_respuesta = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->co_proceso = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = Tb034RevisionPeer::NUM_COLUMNS - Tb034RevisionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Tb034Revision object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTb001UsuarioRelatedByCoUsuarioEnvia !== null && $this->co_usuario_envia !== $this->aTb001UsuarioRelatedByCoUsuarioEnvia->getCoUsuario()) {
			$this->aTb001UsuarioRelatedByCoUsuarioEnvia = null;
		}
		if ($this->aTb001UsuarioRelatedByCoUsuarioResp !== null && $this->co_usuario_resp !== $this->aTb001UsuarioRelatedByCoUsuarioResp->getCoUsuario()) {
			$this->aTb001UsuarioRelatedByCoUsuarioResp = null;
		}
		if ($this->aTb026Solicitud !== null && $this->co_solicitud !== $this->aTb026Solicitud->getCoSolicitud()) {
			$this->aTb026Solicitud = null;
		}
		if ($this->aTb030Ruta !== null && $this->co_ruta !== $this->aTb030Ruta->getCoRuta()) {
			$this->aTb030Ruta = null;
		}
		if ($this->aTb028Proceso !== null && $this->co_proceso !== $this->aTb028Proceso->getCoProceso()) {
			$this->aTb028Proceso = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Tb034RevisionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = Tb034RevisionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTb001UsuarioRelatedByCoUsuarioEnvia = null;
			$this->aTb001UsuarioRelatedByCoUsuarioResp = null;
			$this->aTb026Solicitud = null;
			$this->aTb030Ruta = null;
			$this->aTb028Proceso = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb034Revision:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Tb034RevisionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			Tb034RevisionPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseTb034Revision:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb034Revision:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Tb034RevisionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseTb034Revision:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			Tb034RevisionPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTb001UsuarioRelatedByCoUsuarioEnvia !== null) {
				if ($this->aTb001UsuarioRelatedByCoUsuarioEnvia->isModified() || $this->aTb001UsuarioRelatedByCoUsuarioEnvia->isNew()) {
					$affectedRows += $this->aTb001UsuarioRelatedByCoUsuarioEnvia->save($con);
				}
				$this->setTb001UsuarioRelatedByCoUsuarioEnvia($this->aTb001UsuarioRelatedByCoUsuarioEnvia);
			}

			if ($this->aTb001UsuarioRelatedByCoUsuarioResp !== null) {
				if ($this->aTb001UsuarioRelatedByCoUsuarioResp->isModified() || $this->aTb001UsuarioRelatedByCoUsuarioResp->isNew()) {
					$affectedRows += $this->aTb001UsuarioRelatedByCoUsuarioResp->save($con);
				}
				$this->setTb001UsuarioRelatedByCoUsuarioResp($this->aTb001UsuarioRelatedByCoUsuarioResp);
			}

			if ($this->aTb026Solicitud !== null) {
				if ($this->aTb026Solicitud->isModified() || $this->aTb026Solicitud->isNew()) {
					$affectedRows += $this->aTb026Solicitud->save($con);
				}
				$this->setTb026Solicitud($this->aTb026Solicitud);
			}

			if ($this->aTb030Ruta !== null) {
				if ($this->aTb030Ruta->isModified() || $this->aTb030Ruta->isNew()) {
					$affectedRows += $this->aTb030Ruta->save($con);
				}
				$this->setTb030Ruta($this->aTb030Ruta);
			}

			if ($this->aTb028Proceso !== null) {
				if ($this->aTb028Proceso->isModified() || $this->aTb028Proceso->isNew()) {
					$affectedRows += $this->aTb028Proceso->save($con);
				}
				$this->setTb028Proceso($this->aTb028Proceso);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = Tb034RevisionPeer::CO_REVISION;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = Tb034RevisionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoRevision($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += Tb034RevisionPeer::doUpdate($this, $con);
				}

				// Rewind the im_documento_recibido LOB column, since PDO does not rewind after inserting value.
				if ($this->im_documento_recibido !== null && is_resource($this->im_documento_recibido)) {
					rewind($this->im_documento_recibido);
				}

				// Rewind the im_documento_respuesta LOB column, since PDO does not rewind after inserting value.
				if ($this->im_documento_respuesta !== null && is_resource($this->im_documento_respuesta)) {
					rewind($this->im_documento_respuesta);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTb001UsuarioRelatedByCoUsuarioEnvia !== null) {
				if (!$this->aTb001UsuarioRelatedByCoUsuarioEnvia->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTb001UsuarioRelatedByCoUsuarioEnvia->getValidationFailures());
				}
			}

			if ($this->aTb001UsuarioRelatedByCoUsuarioResp !== null) {
				if (!$this->aTb001UsuarioRelatedByCoUsuarioResp->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTb001UsuarioRelatedByCoUsuarioResp->getValidationFailures());
				}
			}

			if ($this->aTb026Solicitud !== null) {
				if (!$this->aTb026Solicitud->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTb026Solicitud->getValidationFailures());
				}
			}

			if ($this->aTb030Ruta !== null) {
				if (!$this->aTb030Ruta->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTb030Ruta->getValidationFailures());
				}
			}

			if ($this->aTb028Proceso !== null) {
				if (!$this->aTb028Proceso->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTb028Proceso->getValidationFailures());
				}
			}


			if (($retval = Tb034RevisionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Tb034RevisionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoRevision();
				break;
			case 1:
				return $this->getCoUsuarioEnvia();
				break;
			case 2:
				return $this->getTxComentario();
				break;
			case 3:
				return $this->getFeEnvio();
				break;
			case 4:
				return $this->getCoUsuarioResp();
				break;
			case 5:
				return $this->getTxRespuesta();
				break;
			case 6:
				return $this->getFeRespuesta();
				break;
			case 7:
				return $this->getCoSolicitud();
				break;
			case 8:
				return $this->getInActivo();
				break;
			case 9:
				return $this->getCoRuta();
				break;
			case 10:
				return $this->getImDocumentoRecibido();
				break;
			case 11:
				return $this->getMimeDocumentoRecibido();
				break;
			case 12:
				return $this->getImDocumentoRespuesta();
				break;
			case 13:
				return $this->getMimeDocumentoRespuesta();
				break;
			case 14:
				return $this->getCoProceso();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = Tb034RevisionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoRevision(),
			$keys[1] => $this->getCoUsuarioEnvia(),
			$keys[2] => $this->getTxComentario(),
			$keys[3] => $this->getFeEnvio(),
			$keys[4] => $this->getCoUsuarioResp(),
			$keys[5] => $this->getTxRespuesta(),
			$keys[6] => $this->getFeRespuesta(),
			$keys[7] => $this->getCoSolicitud(),
			$keys[8] => $this->getInActivo(),
			$keys[9] => $this->getCoRuta(),
			$keys[10] => $this->getImDocumentoRecibido(),
			$keys[11] => $this->getMimeDocumentoRecibido(),
			$keys[12] => $this->getImDocumentoRespuesta(),
			$keys[13] => $this->getMimeDocumentoRespuesta(),
			$keys[14] => $this->getCoProceso(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Tb034RevisionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoRevision($value);
				break;
			case 1:
				$this->setCoUsuarioEnvia($value);
				break;
			case 2:
				$this->setTxComentario($value);
				break;
			case 3:
				$this->setFeEnvio($value);
				break;
			case 4:
				$this->setCoUsuarioResp($value);
				break;
			case 5:
				$this->setTxRespuesta($value);
				break;
			case 6:
				$this->setFeRespuesta($value);
				break;
			case 7:
				$this->setCoSolicitud($value);
				break;
			case 8:
				$this->setInActivo($value);
				break;
			case 9:
				$this->setCoRuta($value);
				break;
			case 10:
				$this->setImDocumentoRecibido($value);
				break;
			case 11:
				$this->setMimeDocumentoRecibido($value);
				break;
			case 12:
				$this->setImDocumentoRespuesta($value);
				break;
			case 13:
				$this->setMimeDocumentoRespuesta($value);
				break;
			case 14:
				$this->setCoProceso($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = Tb034RevisionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoRevision($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCoUsuarioEnvia($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTxComentario($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFeEnvio($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCoUsuarioResp($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTxRespuesta($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFeRespuesta($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCoSolicitud($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setInActivo($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCoRuta($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setImDocumentoRecibido($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setMimeDocumentoRecibido($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setImDocumentoRespuesta($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setMimeDocumentoRespuesta($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCoProceso($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(Tb034RevisionPeer::DATABASE_NAME);

		if ($this->isColumnModified(Tb034RevisionPeer::CO_REVISION)) $criteria->add(Tb034RevisionPeer::CO_REVISION, $this->co_revision);
		if ($this->isColumnModified(Tb034RevisionPeer::CO_USUARIO_ENVIA)) $criteria->add(Tb034RevisionPeer::CO_USUARIO_ENVIA, $this->co_usuario_envia);
		if ($this->isColumnModified(Tb034RevisionPeer::TX_COMENTARIO)) $criteria->add(Tb034RevisionPeer::TX_COMENTARIO, $this->tx_comentario);
		if ($this->isColumnModified(Tb034RevisionPeer::FE_ENVIO)) $criteria->add(Tb034RevisionPeer::FE_ENVIO, $this->fe_envio);
		if ($this->isColumnModified(Tb034RevisionPeer::CO_USUARIO_RESP)) $criteria->add(Tb034RevisionPeer::CO_USUARIO_RESP, $this->co_usuario_resp);
		if ($this->isColumnModified(Tb034RevisionPeer::TX_RESPUESTA)) $criteria->add(Tb034RevisionPeer::TX_RESPUESTA, $this->tx_respuesta);
		if ($this->isColumnModified(Tb034RevisionPeer::FE_RESPUESTA)) $criteria->add(Tb034RevisionPeer::FE_RESPUESTA, $this->fe_respuesta);
		if ($this->isColumnModified(Tb034RevisionPeer::CO_SOLICITUD)) $criteria->add(Tb034RevisionPeer::CO_SOLICITUD, $this->co_solicitud);
		if ($this->isColumnModified(Tb034RevisionPeer::IN_ACTIVO)) $criteria->add(Tb034RevisionPeer::IN_ACTIVO, $this->in_activo);
		if ($this->isColumnModified(Tb034RevisionPeer::CO_RUTA)) $criteria->add(Tb034RevisionPeer::CO_RUTA, $this->co_ruta);
		if ($this->isColumnModified(Tb034RevisionPeer::IM_DOCUMENTO_RECIBIDO)) $criteria->add(Tb034RevisionPeer::IM_DOCUMENTO_RECIBIDO, $this->im_documento_recibido);
		if ($this->isColumnModified(Tb034RevisionPeer::MIME_DOCUMENTO_RECIBIDO)) $criteria->add(Tb034RevisionPeer::MIME_DOCUMENTO_RECIBIDO, $this->mime_documento_recibido);
		if ($this->isColumnModified(Tb034RevisionPeer::IM_DOCUMENTO_RESPUESTA)) $criteria->add(Tb034RevisionPeer::IM_DOCUMENTO_RESPUESTA, $this->im_documento_respuesta);
		if ($this->isColumnModified(Tb034RevisionPeer::MIME_DOCUMENTO_RESPUESTA)) $criteria->add(Tb034RevisionPeer::MIME_DOCUMENTO_RESPUESTA, $this->mime_documento_respuesta);
		if ($this->isColumnModified(Tb034RevisionPeer::CO_PROCESO)) $criteria->add(Tb034RevisionPeer::CO_PROCESO, $this->co_proceso);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(Tb034RevisionPeer::DATABASE_NAME);

		$criteria->add(Tb034RevisionPeer::CO_REVISION, $this->co_revision);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoRevision();
	}

	/**
	 * Generic method to set the primary key (co_revision column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoRevision($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Tb034Revision (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCoUsuarioEnvia($this->co_usuario_envia);

		$copyObj->setTxComentario($this->tx_comentario);

		$copyObj->setFeEnvio($this->fe_envio);

		$copyObj->setCoUsuarioResp($this->co_usuario_resp);

		$copyObj->setTxRespuesta($this->tx_respuesta);

		$copyObj->setFeRespuesta($this->fe_respuesta);

		$copyObj->setCoSolicitud($this->co_solicitud);

		$copyObj->setInActivo($this->in_activo);

		$copyObj->setCoRuta($this->co_ruta);

		$copyObj->setImDocumentoRecibido($this->im_documento_recibido);

		$copyObj->setMimeDocumentoRecibido($this->mime_documento_recibido);

		$copyObj->setImDocumentoRespuesta($this->im_documento_respuesta);

		$copyObj->setMimeDocumentoRespuesta($this->mime_documento_respuesta);

		$copyObj->setCoProceso($this->co_proceso);


		$copyObj->setNew(true);

		$copyObj->setCoRevision(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Tb034Revision Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     Tb034RevisionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new Tb034RevisionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Tb001Usuario object.
	 *
	 * @param      Tb001Usuario $v
	 * @return     Tb034Revision The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTb001UsuarioRelatedByCoUsuarioEnvia(Tb001Usuario $v = null)
	{
		if ($v === null) {
			$this->setCoUsuarioEnvia(NULL);
		} else {
			$this->setCoUsuarioEnvia($v->getCoUsuario());
		}

		$this->aTb001UsuarioRelatedByCoUsuarioEnvia = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tb001Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addTb034RevisionRelatedByCoUsuarioEnvia($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tb001Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tb001Usuario The associated Tb001Usuario object.
	 * @throws     PropelException
	 */
	public function getTb001UsuarioRelatedByCoUsuarioEnvia(PropelPDO $con = null)
	{
		if ($this->aTb001UsuarioRelatedByCoUsuarioEnvia === null && (($this->co_usuario_envia !== "" && $this->co_usuario_envia !== null))) {
			$c = new Criteria(Tb001UsuarioPeer::DATABASE_NAME);
			$c->add(Tb001UsuarioPeer::CO_USUARIO, $this->co_usuario_envia);
			$this->aTb001UsuarioRelatedByCoUsuarioEnvia = Tb001UsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTb001UsuarioRelatedByCoUsuarioEnvia->addTb034RevisionsRelatedByCoUsuarioEnvia($this);
			 */
		}
		return $this->aTb001UsuarioRelatedByCoUsuarioEnvia;
	}

	/**
	 * Declares an association between this object and a Tb001Usuario object.
	 *
	 * @param      Tb001Usuario $v
	 * @return     Tb034Revision The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTb001UsuarioRelatedByCoUsuarioResp(Tb001Usuario $v = null)
	{
		if ($v === null) {
			$this->setCoUsuarioResp(NULL);
		} else {
			$this->setCoUsuarioResp($v->getCoUsuario());
		}

		$this->aTb001UsuarioRelatedByCoUsuarioResp = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tb001Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addTb034RevisionRelatedByCoUsuarioResp($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tb001Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tb001Usuario The associated Tb001Usuario object.
	 * @throws     PropelException
	 */
	public function getTb001UsuarioRelatedByCoUsuarioResp(PropelPDO $con = null)
	{
		if ($this->aTb001UsuarioRelatedByCoUsuarioResp === null && (($this->co_usuario_resp !== "" && $this->co_usuario_resp !== null))) {
			$c = new Criteria(Tb001UsuarioPeer::DATABASE_NAME);
			$c->add(Tb001UsuarioPeer::CO_USUARIO, $this->co_usuario_resp);
			$this->aTb001UsuarioRelatedByCoUsuarioResp = Tb001UsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTb001UsuarioRelatedByCoUsuarioResp->addTb034RevisionsRelatedByCoUsuarioResp($this);
			 */
		}
		return $this->aTb001UsuarioRelatedByCoUsuarioResp;
	}

	/**
	 * Declares an association between this object and a Tb026Solicitud object.
	 *
	 * @param      Tb026Solicitud $v
	 * @return     Tb034Revision The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTb026Solicitud(Tb026Solicitud $v = null)
	{
		if ($v === null) {
			$this->setCoSolicitud(NULL);
		} else {
			$this->setCoSolicitud($v->getCoSolicitud());
		}

		$this->aTb026Solicitud = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tb026Solicitud object, it will not be re-added.
		if ($v !== null) {
			$v->addTb034Revision($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tb026Solicitud object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tb026Solicitud The associated Tb026Solicitud object.
	 * @throws     PropelException
	 */
	public function getTb026Solicitud(PropelPDO $con = null)
	{
		if ($this->aTb026Solicitud === null && (($this->co_solicitud !== "" && $this->co_solicitud !== null))) {
			$c = new Criteria(Tb026SolicitudPeer::DATABASE_NAME);
			$c->add(Tb026SolicitudPeer::CO_SOLICITUD, $this->co_solicitud);
			$this->aTb026Solicitud = Tb026SolicitudPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTb026Solicitud->addTb034Revisions($this);
			 */
		}
		return $this->aTb026Solicitud;
	}

	/**
	 * Declares an association between this object and a Tb030Ruta object.
	 *
	 * @param      Tb030Ruta $v
	 * @return     Tb034Revision The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTb030Ruta(Tb030Ruta $v = null)
	{
		if ($v === null) {
			$this->setCoRuta(NULL);
		} else {
			$this->setCoRuta($v->getCoRuta());
		}

		$this->aTb030Ruta = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tb030Ruta object, it will not be re-added.
		if ($v !== null) {
			$v->addTb034Revision($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tb030Ruta object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tb030Ruta The associated Tb030Ruta object.
	 * @throws     PropelException
	 */
	public function getTb030Ruta(PropelPDO $con = null)
	{
		if ($this->aTb030Ruta === null && (($this->co_ruta !== "" && $this->co_ruta !== null))) {
			$c = new Criteria(Tb030RutaPeer::DATABASE_NAME);
			$c->add(Tb030RutaPeer::CO_RUTA, $this->co_ruta);
			$this->aTb030Ruta = Tb030RutaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTb030Ruta->addTb034Revisions($this);
			 */
		}
		return $this->aTb030Ruta;
	}

	/**
	 * Declares an association between this object and a Tb028Proceso object.
	 *
	 * @param      Tb028Proceso $v
	 * @return     Tb034Revision The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTb028Proceso(Tb028Proceso $v = null)
	{
		if ($v === null) {
			$this->setCoProceso(NULL);
		} else {
			$this->setCoProceso($v->getCoProceso());
		}

		$this->aTb028Proceso = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tb028Proceso object, it will not be re-added.
		if ($v !== null) {
			$v->addTb034Revision($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tb028Proceso object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tb028Proceso The associated Tb028Proceso object.
	 * @throws     PropelException
	 */
	public function getTb028Proceso(PropelPDO $con = null)
	{
		if ($this->aTb028Proceso === null && (($this->co_proceso !== "" && $this->co_proceso !== null))) {
			$c = new Criteria(Tb028ProcesoPeer::DATABASE_NAME);
			$c->add(Tb028ProcesoPeer::CO_PROCESO, $this->co_proceso);
			$this->aTb028Proceso = Tb028ProcesoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTb028Proceso->addTb034Revisions($this);
			 */
		}
		return $this->aTb028Proceso;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aTb001UsuarioRelatedByCoUsuarioEnvia = null;
			$this->aTb001UsuarioRelatedByCoUsuarioResp = null;
			$this->aTb026Solicitud = null;
			$this->aTb030Ruta = null;
			$this->aTb028Proceso = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseTb034Revision:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseTb034Revision::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseTb034Revision
