<?php

/**
 * Base static class for performing query and update operations on the 'tb015_empresa' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun  6 08:13:27 2022
 *
 * @package    lib.model.om
 */
abstract class BaseTb015EmpresaPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'tb015_empresa';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Tb015Empresa';

	/** The total number of columns. */
	const NUM_COLUMNS = 13;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the CO_EMPRESA field */
	const CO_EMPRESA = 'tb015_empresa.CO_EMPRESA';

	/** the column name for the NB_EMPRESA field */
	const NB_EMPRESA = 'tb015_empresa.NB_EMPRESA';

	/** the column name for the CO_ESTADO field */
	const CO_ESTADO = 'tb015_empresa.CO_ESTADO';

	/** the column name for the CO_MUNICIPIO field */
	const CO_MUNICIPIO = 'tb015_empresa.CO_MUNICIPIO';

	/** the column name for the TX_RIF field */
	const TX_RIF = 'tb015_empresa.TX_RIF';

	/** the column name for the TX_NIT field */
	const TX_NIT = 'tb015_empresa.TX_NIT';

	/** the column name for the TX_DIRECCION field */
	const TX_DIRECCION = 'tb015_empresa.TX_DIRECCION';

	/** the column name for the TX_IMAGEN_DER field */
	const TX_IMAGEN_DER = 'tb015_empresa.TX_IMAGEN_DER';

	/** the column name for the TX_IMAGEN_IZQ field */
	const TX_IMAGEN_IZQ = 'tb015_empresa.TX_IMAGEN_IZQ';

	/** the column name for the TX_IMAGEN_CEN field */
	const TX_IMAGEN_CEN = 'tb015_empresa.TX_IMAGEN_CEN';

	/** the column name for the NU_TELEFONO field */
	const NU_TELEFONO = 'tb015_empresa.NU_TELEFONO';

	/** the column name for the TX_SIGLA field */
	const TX_SIGLA = 'tb015_empresa.TX_SIGLA';

	/** the column name for the OP_IMAGEN field */
	const OP_IMAGEN = 'tb015_empresa.OP_IMAGEN';

	/**
	 * An identiy map to hold any loaded instances of Tb015Empresa objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Tb015Empresa[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('CoEmpresa', 'NbEmpresa', 'CoEstado', 'CoMunicipio', 'TxRif', 'TxNit', 'TxDireccion', 'TxImagenDer', 'TxImagenIzq', 'TxImagenCen', 'NuTelefono', 'TxSigla', 'OpImagen', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('coEmpresa', 'nbEmpresa', 'coEstado', 'coMunicipio', 'txRif', 'txNit', 'txDireccion', 'txImagenDer', 'txImagenIzq', 'txImagenCen', 'nuTelefono', 'txSigla', 'opImagen', ),
		BasePeer::TYPE_COLNAME => array (self::CO_EMPRESA, self::NB_EMPRESA, self::CO_ESTADO, self::CO_MUNICIPIO, self::TX_RIF, self::TX_NIT, self::TX_DIRECCION, self::TX_IMAGEN_DER, self::TX_IMAGEN_IZQ, self::TX_IMAGEN_CEN, self::NU_TELEFONO, self::TX_SIGLA, self::OP_IMAGEN, ),
		BasePeer::TYPE_FIELDNAME => array ('co_empresa', 'nb_empresa', 'co_estado', 'co_municipio', 'tx_rif', 'tx_nit', 'tx_direccion', 'tx_imagen_der', 'tx_imagen_izq', 'tx_imagen_cen', 'nu_telefono', 'tx_sigla', 'op_imagen', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('CoEmpresa' => 0, 'NbEmpresa' => 1, 'CoEstado' => 2, 'CoMunicipio' => 3, 'TxRif' => 4, 'TxNit' => 5, 'TxDireccion' => 6, 'TxImagenDer' => 7, 'TxImagenIzq' => 8, 'TxImagenCen' => 9, 'NuTelefono' => 10, 'TxSigla' => 11, 'OpImagen' => 12, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('coEmpresa' => 0, 'nbEmpresa' => 1, 'coEstado' => 2, 'coMunicipio' => 3, 'txRif' => 4, 'txNit' => 5, 'txDireccion' => 6, 'txImagenDer' => 7, 'txImagenIzq' => 8, 'txImagenCen' => 9, 'nuTelefono' => 10, 'txSigla' => 11, 'opImagen' => 12, ),
		BasePeer::TYPE_COLNAME => array (self::CO_EMPRESA => 0, self::NB_EMPRESA => 1, self::CO_ESTADO => 2, self::CO_MUNICIPIO => 3, self::TX_RIF => 4, self::TX_NIT => 5, self::TX_DIRECCION => 6, self::TX_IMAGEN_DER => 7, self::TX_IMAGEN_IZQ => 8, self::TX_IMAGEN_CEN => 9, self::NU_TELEFONO => 10, self::TX_SIGLA => 11, self::OP_IMAGEN => 12, ),
		BasePeer::TYPE_FIELDNAME => array ('co_empresa' => 0, 'nb_empresa' => 1, 'co_estado' => 2, 'co_municipio' => 3, 'tx_rif' => 4, 'tx_nit' => 5, 'tx_direccion' => 6, 'tx_imagen_der' => 7, 'tx_imagen_izq' => 8, 'tx_imagen_cen' => 9, 'nu_telefono' => 10, 'tx_sigla' => 11, 'op_imagen' => 12, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new Tb015EmpresaMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. Tb015EmpresaPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(Tb015EmpresaPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(Tb015EmpresaPeer::CO_EMPRESA);

		$criteria->addSelectColumn(Tb015EmpresaPeer::NB_EMPRESA);

		$criteria->addSelectColumn(Tb015EmpresaPeer::CO_ESTADO);

		$criteria->addSelectColumn(Tb015EmpresaPeer::CO_MUNICIPIO);

		$criteria->addSelectColumn(Tb015EmpresaPeer::TX_RIF);

		$criteria->addSelectColumn(Tb015EmpresaPeer::TX_NIT);

		$criteria->addSelectColumn(Tb015EmpresaPeer::TX_DIRECCION);

		$criteria->addSelectColumn(Tb015EmpresaPeer::TX_IMAGEN_DER);

		$criteria->addSelectColumn(Tb015EmpresaPeer::TX_IMAGEN_IZQ);

		$criteria->addSelectColumn(Tb015EmpresaPeer::TX_IMAGEN_CEN);

		$criteria->addSelectColumn(Tb015EmpresaPeer::NU_TELEFONO);

		$criteria->addSelectColumn(Tb015EmpresaPeer::TX_SIGLA);

		$criteria->addSelectColumn(Tb015EmpresaPeer::OP_IMAGEN);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb015EmpresaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb015EmpresaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Tb015Empresa
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = Tb015EmpresaPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return Tb015EmpresaPeer::populateObjects(Tb015EmpresaPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			Tb015EmpresaPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Tb015Empresa $value A Tb015Empresa object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Tb015Empresa $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getCoEmpresa();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Tb015Empresa object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Tb015Empresa) {
				$key = (string) $value->getCoEmpresa();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Tb015Empresa object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Tb015Empresa Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = Tb015EmpresaPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = Tb015EmpresaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = Tb015EmpresaPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				Tb015EmpresaPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Tb016Estado table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb016Estado(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb015EmpresaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb015EmpresaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb015EmpresaPeer::CO_ESTADO,), array(Tb016EstadoPeer::CO_ESTADO,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb017Municipio table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb017Municipio(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb015EmpresaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb015EmpresaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb015EmpresaPeer::CO_MUNICIPIO,), array(Tb017MunicipioPeer::CO_MUNICIPIO,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Tb015Empresa objects pre-filled with their Tb016Estado objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb015Empresa objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb016Estado(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb015EmpresaPeer::addSelectColumns($c);
		$startcol = (Tb015EmpresaPeer::NUM_COLUMNS - Tb015EmpresaPeer::NUM_LAZY_LOAD_COLUMNS);
		Tb016EstadoPeer::addSelectColumns($c);

		$c->addJoin(array(Tb015EmpresaPeer::CO_ESTADO,), array(Tb016EstadoPeer::CO_ESTADO,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb015EmpresaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb015EmpresaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb015EmpresaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb015EmpresaPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb016EstadoPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb016EstadoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb016EstadoPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb016EstadoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb015Empresa) to $obj2 (Tb016Estado)
				$obj2->addTb015Empresa($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb015Empresa objects pre-filled with their Tb017Municipio objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb015Empresa objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb017Municipio(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb015EmpresaPeer::addSelectColumns($c);
		$startcol = (Tb015EmpresaPeer::NUM_COLUMNS - Tb015EmpresaPeer::NUM_LAZY_LOAD_COLUMNS);
		Tb017MunicipioPeer::addSelectColumns($c);

		$c->addJoin(array(Tb015EmpresaPeer::CO_MUNICIPIO,), array(Tb017MunicipioPeer::CO_MUNICIPIO,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb015EmpresaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb015EmpresaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb015EmpresaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb015EmpresaPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb017MunicipioPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb017MunicipioPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb017MunicipioPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb017MunicipioPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb015Empresa) to $obj2 (Tb017Municipio)
				$obj2->addTb015Empresa($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb015EmpresaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb015EmpresaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb015EmpresaPeer::CO_ESTADO,), array(Tb016EstadoPeer::CO_ESTADO,), $join_behavior);
		$criteria->addJoin(array(Tb015EmpresaPeer::CO_MUNICIPIO,), array(Tb017MunicipioPeer::CO_MUNICIPIO,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Tb015Empresa objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb015Empresa objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb015EmpresaPeer::addSelectColumns($c);
		$startcol2 = (Tb015EmpresaPeer::NUM_COLUMNS - Tb015EmpresaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb016EstadoPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb016EstadoPeer::NUM_COLUMNS - Tb016EstadoPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb017MunicipioPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb017MunicipioPeer::NUM_COLUMNS - Tb017MunicipioPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(Tb015EmpresaPeer::CO_ESTADO,), array(Tb016EstadoPeer::CO_ESTADO,), $join_behavior);
		$c->addJoin(array(Tb015EmpresaPeer::CO_MUNICIPIO,), array(Tb017MunicipioPeer::CO_MUNICIPIO,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb015EmpresaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb015EmpresaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb015EmpresaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb015EmpresaPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Tb016Estado rows

			$key2 = Tb016EstadoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = Tb016EstadoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb016EstadoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb016EstadoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Tb015Empresa) to the collection in $obj2 (Tb016Estado)
				$obj2->addTb015Empresa($obj1);
			} // if joined row not null

			// Add objects for joined Tb017Municipio rows

			$key3 = Tb017MunicipioPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = Tb017MunicipioPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = Tb017MunicipioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb017MunicipioPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Tb015Empresa) to the collection in $obj3 (Tb017Municipio)
				$obj3->addTb015Empresa($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb016Estado table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb016Estado(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb015EmpresaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb015EmpresaPeer::CO_MUNICIPIO,), array(Tb017MunicipioPeer::CO_MUNICIPIO,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb017Municipio table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb017Municipio(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb015EmpresaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb015EmpresaPeer::CO_ESTADO,), array(Tb016EstadoPeer::CO_ESTADO,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Tb015Empresa objects pre-filled with all related objects except Tb016Estado.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb015Empresa objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb016Estado(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb015EmpresaPeer::addSelectColumns($c);
		$startcol2 = (Tb015EmpresaPeer::NUM_COLUMNS - Tb015EmpresaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb017MunicipioPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb017MunicipioPeer::NUM_COLUMNS - Tb017MunicipioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb015EmpresaPeer::CO_MUNICIPIO,), array(Tb017MunicipioPeer::CO_MUNICIPIO,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb015EmpresaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb015EmpresaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb015EmpresaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb015EmpresaPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb017Municipio rows

				$key2 = Tb017MunicipioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb017MunicipioPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb017MunicipioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb017MunicipioPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb015Empresa) to the collection in $obj2 (Tb017Municipio)
				$obj2->addTb015Empresa($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb015Empresa objects pre-filled with all related objects except Tb017Municipio.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb015Empresa objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb017Municipio(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb015EmpresaPeer::addSelectColumns($c);
		$startcol2 = (Tb015EmpresaPeer::NUM_COLUMNS - Tb015EmpresaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb016EstadoPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb016EstadoPeer::NUM_COLUMNS - Tb016EstadoPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb015EmpresaPeer::CO_ESTADO,), array(Tb016EstadoPeer::CO_ESTADO,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb015EmpresaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb015EmpresaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb015EmpresaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb015EmpresaPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb016Estado rows

				$key2 = Tb016EstadoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb016EstadoPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb016EstadoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb016EstadoPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb015Empresa) to the collection in $obj2 (Tb016Estado)
				$obj2->addTb015Empresa($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return Tb015EmpresaPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Tb015Empresa or Criteria object.
	 *
	 * @param      mixed $values Criteria or Tb015Empresa object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseTb015EmpresaPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Tb015Empresa object
		}

		if ($criteria->containsKey(Tb015EmpresaPeer::CO_EMPRESA) && $criteria->keyContainsValue(Tb015EmpresaPeer::CO_EMPRESA) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.Tb015EmpresaPeer::CO_EMPRESA.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Tb015Empresa or Criteria object.
	 *
	 * @param      mixed $values Criteria or Tb015Empresa object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseTb015EmpresaPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(Tb015EmpresaPeer::CO_EMPRESA);
			$selectCriteria->add(Tb015EmpresaPeer::CO_EMPRESA, $criteria->remove(Tb015EmpresaPeer::CO_EMPRESA), $comparison);

		} else { // $values is Tb015Empresa object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseTb015EmpresaPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseTb015EmpresaPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the tb015_empresa table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(Tb015EmpresaPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Tb015Empresa or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Tb015Empresa object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			Tb015EmpresaPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Tb015Empresa) {
			// invalidate the cache for this single object
			Tb015EmpresaPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(Tb015EmpresaPeer::CO_EMPRESA, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				Tb015EmpresaPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Tb015Empresa object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Tb015Empresa $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Tb015Empresa $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(Tb015EmpresaPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(Tb015EmpresaPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(Tb015EmpresaPeer::DATABASE_NAME, Tb015EmpresaPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = Tb015EmpresaPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      string $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Tb015Empresa
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = Tb015EmpresaPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(Tb015EmpresaPeer::DATABASE_NAME);
		$criteria->add(Tb015EmpresaPeer::CO_EMPRESA, $pk);

		$v = Tb015EmpresaPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(Tb015EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(Tb015EmpresaPeer::DATABASE_NAME);
			$criteria->add(Tb015EmpresaPeer::CO_EMPRESA, $pks, Criteria::IN);
			$objs = Tb015EmpresaPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseTb015EmpresaPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the Tb015EmpresaPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the Tb015EmpresaPeer class:
//
// Propel::getDatabaseMap(Tb015EmpresaPeer::DATABASE_NAME)->addTableBuilder(Tb015EmpresaPeer::TABLE_NAME, Tb015EmpresaPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseTb015EmpresaPeer::DATABASE_NAME)->addTableBuilder(BaseTb015EmpresaPeer::TABLE_NAME, BaseTb015EmpresaPeer::getMapBuilder());

