<?php

/**
 * Base static class for performing query and update operations on the 'tb059_cambio_partida_compra' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun  6 08:13:29 2022
 *
 * @package    lib.model.om
 */
abstract class BaseTb059CambioPartidaCompraPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'tb059_cambio_partida_compra';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Tb059CambioPartidaCompra';

	/** The total number of columns. */
	const NUM_COLUMNS = 11;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the CO_CAMBIO_PARTIDA field */
	const CO_CAMBIO_PARTIDA = 'tb059_cambio_partida_compra.CO_CAMBIO_PARTIDA';

	/** the column name for the CO_DETALLE_COMPRA field */
	const CO_DETALLE_COMPRA = 'tb059_cambio_partida_compra.CO_DETALLE_COMPRA';

	/** the column name for the CO_PARTIDA_ANTERIOR field */
	const CO_PARTIDA_ANTERIOR = 'tb059_cambio_partida_compra.CO_PARTIDA_ANTERIOR';

	/** the column name for the CO_PARTIDA_ACTUAL field */
	const CO_PARTIDA_ACTUAL = 'tb059_cambio_partida_compra.CO_PARTIDA_ACTUAL';

	/** the column name for the CO_USUARIO field */
	const CO_USUARIO = 'tb059_cambio_partida_compra.CO_USUARIO';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'tb059_cambio_partida_compra.CREATED_AT';

	/** the column name for the TX_MOTIVO field */
	const TX_MOTIVO = 'tb059_cambio_partida_compra.TX_MOTIVO';

	/** the column name for the CO_PRESUPUESTO_ACTUAL field */
	const CO_PRESUPUESTO_ACTUAL = 'tb059_cambio_partida_compra.CO_PRESUPUESTO_ACTUAL';

	/** the column name for the CO_PRESUPUESTO_ANTERIOR field */
	const CO_PRESUPUESTO_ANTERIOR = 'tb059_cambio_partida_compra.CO_PRESUPUESTO_ANTERIOR';

	/** the column name for the CO_SOLICITUD_ANULAR field */
	const CO_SOLICITUD_ANULAR = 'tb059_cambio_partida_compra.CO_SOLICITUD_ANULAR';

	/** the column name for the IN_ANULAR field */
	const IN_ANULAR = 'tb059_cambio_partida_compra.IN_ANULAR';

	/**
	 * An identiy map to hold any loaded instances of Tb059CambioPartidaCompra objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Tb059CambioPartidaCompra[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('CoCambioPartida', 'CoDetalleCompra', 'CoPartidaAnterior', 'CoPartidaActual', 'CoUsuario', 'CreatedAt', 'TxMotivo', 'CoPresupuestoActual', 'CoPresupuestoAnterior', 'CoSolicitudAnular', 'InAnular', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('coCambioPartida', 'coDetalleCompra', 'coPartidaAnterior', 'coPartidaActual', 'coUsuario', 'createdAt', 'txMotivo', 'coPresupuestoActual', 'coPresupuestoAnterior', 'coSolicitudAnular', 'inAnular', ),
		BasePeer::TYPE_COLNAME => array (self::CO_CAMBIO_PARTIDA, self::CO_DETALLE_COMPRA, self::CO_PARTIDA_ANTERIOR, self::CO_PARTIDA_ACTUAL, self::CO_USUARIO, self::CREATED_AT, self::TX_MOTIVO, self::CO_PRESUPUESTO_ACTUAL, self::CO_PRESUPUESTO_ANTERIOR, self::CO_SOLICITUD_ANULAR, self::IN_ANULAR, ),
		BasePeer::TYPE_FIELDNAME => array ('co_cambio_partida', 'co_detalle_compra', 'co_partida_anterior', 'co_partida_actual', 'co_usuario', 'created_at', 'tx_motivo', 'co_presupuesto_actual', 'co_presupuesto_anterior', 'co_solicitud_anular', 'in_anular', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('CoCambioPartida' => 0, 'CoDetalleCompra' => 1, 'CoPartidaAnterior' => 2, 'CoPartidaActual' => 3, 'CoUsuario' => 4, 'CreatedAt' => 5, 'TxMotivo' => 6, 'CoPresupuestoActual' => 7, 'CoPresupuestoAnterior' => 8, 'CoSolicitudAnular' => 9, 'InAnular' => 10, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('coCambioPartida' => 0, 'coDetalleCompra' => 1, 'coPartidaAnterior' => 2, 'coPartidaActual' => 3, 'coUsuario' => 4, 'createdAt' => 5, 'txMotivo' => 6, 'coPresupuestoActual' => 7, 'coPresupuestoAnterior' => 8, 'coSolicitudAnular' => 9, 'inAnular' => 10, ),
		BasePeer::TYPE_COLNAME => array (self::CO_CAMBIO_PARTIDA => 0, self::CO_DETALLE_COMPRA => 1, self::CO_PARTIDA_ANTERIOR => 2, self::CO_PARTIDA_ACTUAL => 3, self::CO_USUARIO => 4, self::CREATED_AT => 5, self::TX_MOTIVO => 6, self::CO_PRESUPUESTO_ACTUAL => 7, self::CO_PRESUPUESTO_ANTERIOR => 8, self::CO_SOLICITUD_ANULAR => 9, self::IN_ANULAR => 10, ),
		BasePeer::TYPE_FIELDNAME => array ('co_cambio_partida' => 0, 'co_detalle_compra' => 1, 'co_partida_anterior' => 2, 'co_partida_actual' => 3, 'co_usuario' => 4, 'created_at' => 5, 'tx_motivo' => 6, 'co_presupuesto_actual' => 7, 'co_presupuesto_anterior' => 8, 'co_solicitud_anular' => 9, 'in_anular' => 10, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new Tb059CambioPartidaCompraMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. Tb059CambioPartidaCompraPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(Tb059CambioPartidaCompraPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::CO_DETALLE_COMPRA);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::CO_USUARIO);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::CREATED_AT);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::TX_MOTIVO);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::CO_SOLICITUD_ANULAR);

		$criteria->addSelectColumn(Tb059CambioPartidaCompraPeer::IN_ANULAR);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb059CambioPartidaCompraPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Tb059CambioPartidaCompra
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = Tb059CambioPartidaCompraPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return Tb059CambioPartidaCompraPeer::populateObjects(Tb059CambioPartidaCompraPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Tb059CambioPartidaCompra $value A Tb059CambioPartidaCompra object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Tb059CambioPartidaCompra $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getCoCambioPartida();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Tb059CambioPartidaCompra object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Tb059CambioPartidaCompra) {
				$key = (string) $value->getCoCambioPartida();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Tb059CambioPartidaCompra object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Tb059CambioPartidaCompra Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = Tb059CambioPartidaCompraPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Tb091PartidaRelatedByCoPartidaAnterior table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb091PartidaRelatedByCoPartidaAnterior(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb059CambioPartidaCompraPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb091PartidaRelatedByCoPartidaActual table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb091PartidaRelatedByCoPartidaActual(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb059CambioPartidaCompraPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb001Usuario table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb001Usuario(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb059CambioPartidaCompraPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb085PresupuestoRelatedByCoPresupuestoActual table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb085PresupuestoRelatedByCoPresupuestoActual(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb059CambioPartidaCompraPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb085PresupuestoRelatedByCoPresupuestoAnterior table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb085PresupuestoRelatedByCoPresupuestoAnterior(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb059CambioPartidaCompraPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with their Tb091Partida objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb091PartidaRelatedByCoPartidaAnterior(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);
		Tb091PartidaPeer::addSelectColumns($c);

		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb091PartidaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb091PartidaPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb091PartidaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to $obj2 (Tb091Partida)
				$obj2->addTb059CambioPartidaCompraRelatedByCoPartidaAnterior($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with their Tb091Partida objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb091PartidaRelatedByCoPartidaActual(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);
		Tb091PartidaPeer::addSelectColumns($c);

		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb091PartidaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb091PartidaPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb091PartidaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to $obj2 (Tb091Partida)
				$obj2->addTb059CambioPartidaCompraRelatedByCoPartidaActual($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with their Tb001Usuario objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb001Usuario(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);
		Tb001UsuarioPeer::addSelectColumns($c);

		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb001UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb001UsuarioPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb001UsuarioPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb001UsuarioPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to $obj2 (Tb001Usuario)
				$obj2->addTb059CambioPartidaCompra($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with their Tb085Presupuesto objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb085PresupuestoRelatedByCoPresupuestoActual(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);
		Tb085PresupuestoPeer::addSelectColumns($c);

		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb085PresupuestoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb085PresupuestoPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb085PresupuestoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to $obj2 (Tb085Presupuesto)
				$obj2->addTb059CambioPartidaCompraRelatedByCoPresupuestoActual($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with their Tb085Presupuesto objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb085PresupuestoRelatedByCoPresupuestoAnterior(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);
		Tb085PresupuestoPeer::addSelectColumns($c);

		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb085PresupuestoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb085PresupuestoPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb085PresupuestoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to $obj2 (Tb085Presupuesto)
				$obj2->addTb059CambioPartidaCompraRelatedByCoPresupuestoAnterior($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb059CambioPartidaCompraPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);
		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);
		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);
		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
		$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol2 = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb091PartidaPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb091PartidaPeer::NUM_COLUMNS - Tb091PartidaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb091PartidaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb091PartidaPeer::NUM_COLUMNS - Tb091PartidaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb001UsuarioPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (Tb001UsuarioPeer::NUM_COLUMNS - Tb001UsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol7 = $startcol6 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);
		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);
		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);
		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
		$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Tb091Partida rows

			$key2 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = Tb091PartidaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb091PartidaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb091PartidaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj2 (Tb091Partida)
				$obj2->addTb059CambioPartidaCompraRelatedByCoPartidaAnterior($obj1);
			} // if joined row not null

			// Add objects for joined Tb091Partida rows

			$key3 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = Tb091PartidaPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = Tb091PartidaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb091PartidaPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj3 (Tb091Partida)
				$obj3->addTb059CambioPartidaCompraRelatedByCoPartidaActual($obj1);
			} // if joined row not null

			// Add objects for joined Tb001Usuario rows

			$key4 = Tb001UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = Tb001UsuarioPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = Tb001UsuarioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					Tb001UsuarioPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj4 (Tb001Usuario)
				$obj4->addTb059CambioPartidaCompra($obj1);
			} // if joined row not null

			// Add objects for joined Tb085Presupuesto rows

			$key5 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = Tb085PresupuestoPeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					Tb085PresupuestoPeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj5 (Tb085Presupuesto)
				$obj5->addTb059CambioPartidaCompraRelatedByCoPresupuestoActual($obj1);
			} // if joined row not null

			// Add objects for joined Tb085Presupuesto rows

			$key6 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol6);
			if ($key6 !== null) {
				$obj6 = Tb085PresupuestoPeer::getInstanceFromPool($key6);
				if (!$obj6) {

					$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj6 = new $cls();
					$obj6->hydrate($row, $startcol6);
					Tb085PresupuestoPeer::addInstanceToPool($obj6, $key6);
				} // if obj6 loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj6 (Tb085Presupuesto)
				$obj6->addTb059CambioPartidaCompraRelatedByCoPresupuestoAnterior($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb091PartidaRelatedByCoPartidaAnterior table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb091PartidaRelatedByCoPartidaAnterior(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb091PartidaRelatedByCoPartidaActual table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb091PartidaRelatedByCoPartidaActual(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb001Usuario table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb001Usuario(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb085PresupuestoRelatedByCoPresupuestoActual table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb085PresupuestoRelatedByCoPresupuestoActual(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb085PresupuestoRelatedByCoPresupuestoAnterior table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb085PresupuestoRelatedByCoPresupuestoAnterior(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb059CambioPartidaCompraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with all related objects except Tb091PartidaRelatedByCoPartidaAnterior.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb091PartidaRelatedByCoPartidaAnterior(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol2 = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb001UsuarioPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb001UsuarioPeer::NUM_COLUMNS - Tb001UsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb001Usuario rows

				$key2 = Tb001UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb001UsuarioPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb001UsuarioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb001UsuarioPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj2 (Tb001Usuario)
				$obj2->addTb059CambioPartidaCompra($obj1);

			} // if joined row is not null

				// Add objects for joined Tb085Presupuesto rows

				$key3 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = Tb085PresupuestoPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb085PresupuestoPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj3 (Tb085Presupuesto)
				$obj3->addTb059CambioPartidaCompraRelatedByCoPresupuestoActual($obj1);

			} // if joined row is not null

				// Add objects for joined Tb085Presupuesto rows

				$key4 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = Tb085PresupuestoPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					Tb085PresupuestoPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj4 (Tb085Presupuesto)
				$obj4->addTb059CambioPartidaCompraRelatedByCoPresupuestoAnterior($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with all related objects except Tb091PartidaRelatedByCoPartidaActual.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb091PartidaRelatedByCoPartidaActual(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol2 = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb001UsuarioPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb001UsuarioPeer::NUM_COLUMNS - Tb001UsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb001Usuario rows

				$key2 = Tb001UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb001UsuarioPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb001UsuarioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb001UsuarioPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj2 (Tb001Usuario)
				$obj2->addTb059CambioPartidaCompra($obj1);

			} // if joined row is not null

				// Add objects for joined Tb085Presupuesto rows

				$key3 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = Tb085PresupuestoPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb085PresupuestoPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj3 (Tb085Presupuesto)
				$obj3->addTb059CambioPartidaCompraRelatedByCoPresupuestoActual($obj1);

			} // if joined row is not null

				// Add objects for joined Tb085Presupuesto rows

				$key4 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = Tb085PresupuestoPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					Tb085PresupuestoPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj4 (Tb085Presupuesto)
				$obj4->addTb059CambioPartidaCompraRelatedByCoPresupuestoAnterior($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with all related objects except Tb001Usuario.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb001Usuario(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol2 = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb091PartidaPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb091PartidaPeer::NUM_COLUMNS - Tb091PartidaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb091PartidaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb091PartidaPeer::NUM_COLUMNS - Tb091PartidaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ACTUAL,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PRESUPUESTO_ANTERIOR,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb091Partida rows

				$key2 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb091PartidaPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb091PartidaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb091PartidaPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj2 (Tb091Partida)
				$obj2->addTb059CambioPartidaCompraRelatedByCoPartidaAnterior($obj1);

			} // if joined row is not null

				// Add objects for joined Tb091Partida rows

				$key3 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = Tb091PartidaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = Tb091PartidaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb091PartidaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj3 (Tb091Partida)
				$obj3->addTb059CambioPartidaCompraRelatedByCoPartidaActual($obj1);

			} // if joined row is not null

				// Add objects for joined Tb085Presupuesto rows

				$key4 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = Tb085PresupuestoPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					Tb085PresupuestoPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj4 (Tb085Presupuesto)
				$obj4->addTb059CambioPartidaCompraRelatedByCoPresupuestoActual($obj1);

			} // if joined row is not null

				// Add objects for joined Tb085Presupuesto rows

				$key5 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = Tb085PresupuestoPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					Tb085PresupuestoPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj5 (Tb085Presupuesto)
				$obj5->addTb059CambioPartidaCompraRelatedByCoPresupuestoAnterior($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with all related objects except Tb085PresupuestoRelatedByCoPresupuestoActual.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb085PresupuestoRelatedByCoPresupuestoActual(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol2 = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb091PartidaPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb091PartidaPeer::NUM_COLUMNS - Tb091PartidaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb091PartidaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb091PartidaPeer::NUM_COLUMNS - Tb091PartidaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb001UsuarioPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (Tb001UsuarioPeer::NUM_COLUMNS - Tb001UsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb091Partida rows

				$key2 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb091PartidaPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb091PartidaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb091PartidaPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj2 (Tb091Partida)
				$obj2->addTb059CambioPartidaCompraRelatedByCoPartidaAnterior($obj1);

			} // if joined row is not null

				// Add objects for joined Tb091Partida rows

				$key3 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = Tb091PartidaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = Tb091PartidaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb091PartidaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj3 (Tb091Partida)
				$obj3->addTb059CambioPartidaCompraRelatedByCoPartidaActual($obj1);

			} // if joined row is not null

				// Add objects for joined Tb001Usuario rows

				$key4 = Tb001UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = Tb001UsuarioPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = Tb001UsuarioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					Tb001UsuarioPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj4 (Tb001Usuario)
				$obj4->addTb059CambioPartidaCompra($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb059CambioPartidaCompra objects pre-filled with all related objects except Tb085PresupuestoRelatedByCoPresupuestoAnterior.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb059CambioPartidaCompra objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb085PresupuestoRelatedByCoPresupuestoAnterior(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb059CambioPartidaCompraPeer::addSelectColumns($c);
		$startcol2 = (Tb059CambioPartidaCompraPeer::NUM_COLUMNS - Tb059CambioPartidaCompraPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb091PartidaPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb091PartidaPeer::NUM_COLUMNS - Tb091PartidaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb091PartidaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb091PartidaPeer::NUM_COLUMNS - Tb091PartidaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb001UsuarioPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (Tb001UsuarioPeer::NUM_COLUMNS - Tb001UsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ANTERIOR,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_PARTIDA_ACTUAL,), array(Tb091PartidaPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb059CambioPartidaCompraPeer::CO_USUARIO,), array(Tb001UsuarioPeer::CO_USUARIO,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb059CambioPartidaCompraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb059CambioPartidaCompraPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb059CambioPartidaCompraPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb059CambioPartidaCompraPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb091Partida rows

				$key2 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb091PartidaPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb091PartidaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb091PartidaPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj2 (Tb091Partida)
				$obj2->addTb059CambioPartidaCompraRelatedByCoPartidaAnterior($obj1);

			} // if joined row is not null

				// Add objects for joined Tb091Partida rows

				$key3 = Tb091PartidaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = Tb091PartidaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = Tb091PartidaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb091PartidaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj3 (Tb091Partida)
				$obj3->addTb059CambioPartidaCompraRelatedByCoPartidaActual($obj1);

			} // if joined row is not null

				// Add objects for joined Tb001Usuario rows

				$key4 = Tb001UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = Tb001UsuarioPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = Tb001UsuarioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					Tb001UsuarioPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tb059CambioPartidaCompra) to the collection in $obj4 (Tb001Usuario)
				$obj4->addTb059CambioPartidaCompra($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return Tb059CambioPartidaCompraPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Tb059CambioPartidaCompra or Criteria object.
	 *
	 * @param      mixed $values Criteria or Tb059CambioPartidaCompra object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Tb059CambioPartidaCompra object
		}

		if ($criteria->containsKey(Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA) && $criteria->keyContainsValue(Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Tb059CambioPartidaCompra or Criteria object.
	 *
	 * @param      mixed $values Criteria or Tb059CambioPartidaCompra object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA);
			$selectCriteria->add(Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA, $criteria->remove(Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA), $comparison);

		} else { // $values is Tb059CambioPartidaCompra object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseTb059CambioPartidaCompraPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseTb059CambioPartidaCompraPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the tb059_cambio_partida_compra table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(Tb059CambioPartidaCompraPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Tb059CambioPartidaCompra or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Tb059CambioPartidaCompra object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			Tb059CambioPartidaCompraPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Tb059CambioPartidaCompra) {
			// invalidate the cache for this single object
			Tb059CambioPartidaCompraPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				Tb059CambioPartidaCompraPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Tb059CambioPartidaCompra object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Tb059CambioPartidaCompra $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Tb059CambioPartidaCompra $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(Tb059CambioPartidaCompraPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(Tb059CambioPartidaCompraPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Tb059CambioPartidaCompraPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = Tb059CambioPartidaCompraPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      string $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Tb059CambioPartidaCompra
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = Tb059CambioPartidaCompraPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(Tb059CambioPartidaCompraPeer::DATABASE_NAME);
		$criteria->add(Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA, $pk);

		$v = Tb059CambioPartidaCompraPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(Tb059CambioPartidaCompraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(Tb059CambioPartidaCompraPeer::DATABASE_NAME);
			$criteria->add(Tb059CambioPartidaCompraPeer::CO_CAMBIO_PARTIDA, $pks, Criteria::IN);
			$objs = Tb059CambioPartidaCompraPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseTb059CambioPartidaCompraPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the Tb059CambioPartidaCompraPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the Tb059CambioPartidaCompraPeer class:
//
// Propel::getDatabaseMap(Tb059CambioPartidaCompraPeer::DATABASE_NAME)->addTableBuilder(Tb059CambioPartidaCompraPeer::TABLE_NAME, Tb059CambioPartidaCompraPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseTb059CambioPartidaCompraPeer::DATABASE_NAME)->addTableBuilder(BaseTb059CambioPartidaCompraPeer::TABLE_NAME, BaseTb059CambioPartidaCompraPeer::getMapBuilder());

