<?php

/**
 * Base class that represents a row from the 'tbrh067_grupo_nomina' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Jan  7 13:26:54 2022
 *
 * @package    lib.model.om
 */
abstract class BaseTbrh067GrupoNomina extends BaseObject  implements Persistent {


  const PEER = 'Tbrh067GrupoNominaPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        Tbrh067GrupoNominaPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_grupo_nomina field.
	 * @var        string
	 */
	protected $co_grupo_nomina;

	/**
	 * The value for the tx_grupo_nomina field.
	 * @var        string
	 */
	protected $tx_grupo_nomina;

	/**
	 * The value for the co_tp_nomina field.
	 * @var        string
	 */
	protected $co_tp_nomina;

	/**
	 * The value for the cod_grupo_nomina field.
	 * @var        string
	 */
	protected $cod_grupo_nomina;

	/**
	 * @var        array Tbrh070PrimaAntiguedad[] Collection to store aggregation of Tbrh070PrimaAntiguedad objects.
	 */
	protected $collTbrh070PrimaAntiguedads;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTbrh070PrimaAntiguedads.
	 */
	private $lastTbrh070PrimaAntiguedadCriteria = null;

	/**
	 * @var        array Tbrh098ConceptoTiempo[] Collection to store aggregation of Tbrh098ConceptoTiempo objects.
	 */
	protected $collTbrh098ConceptoTiempos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTbrh098ConceptoTiempos.
	 */
	private $lastTbrh098ConceptoTiempoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseTbrh067GrupoNomina object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_grupo_nomina] column value.
	 * 
	 * @return     string
	 */
	public function getCoGrupoNomina()
	{
		return $this->co_grupo_nomina;
	}

	/**
	 * Get the [tx_grupo_nomina] column value.
	 * 
	 * @return     string
	 */
	public function getTxGrupoNomina()
	{
		return $this->tx_grupo_nomina;
	}

	/**
	 * Get the [co_tp_nomina] column value.
	 * 
	 * @return     string
	 */
	public function getCoTpNomina()
	{
		return $this->co_tp_nomina;
	}

	/**
	 * Get the [cod_grupo_nomina] column value.
	 * 
	 * @return     string
	 */
	public function getCodGrupoNomina()
	{
		return $this->cod_grupo_nomina;
	}

	/**
	 * Set the value of [co_grupo_nomina] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbrh067GrupoNomina The current object (for fluent API support)
	 */
	public function setCoGrupoNomina($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_grupo_nomina !== $v) {
			$this->co_grupo_nomina = $v;
			$this->modifiedColumns[] = Tbrh067GrupoNominaPeer::CO_GRUPO_NOMINA;
		}

		return $this;
	} // setCoGrupoNomina()

	/**
	 * Set the value of [tx_grupo_nomina] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbrh067GrupoNomina The current object (for fluent API support)
	 */
	public function setTxGrupoNomina($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_grupo_nomina !== $v) {
			$this->tx_grupo_nomina = $v;
			$this->modifiedColumns[] = Tbrh067GrupoNominaPeer::TX_GRUPO_NOMINA;
		}

		return $this;
	} // setTxGrupoNomina()

	/**
	 * Set the value of [co_tp_nomina] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbrh067GrupoNomina The current object (for fluent API support)
	 */
	public function setCoTpNomina($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_tp_nomina !== $v) {
			$this->co_tp_nomina = $v;
			$this->modifiedColumns[] = Tbrh067GrupoNominaPeer::CO_TP_NOMINA;
		}

		return $this;
	} // setCoTpNomina()

	/**
	 * Set the value of [cod_grupo_nomina] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbrh067GrupoNomina The current object (for fluent API support)
	 */
	public function setCodGrupoNomina($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cod_grupo_nomina !== $v) {
			$this->cod_grupo_nomina = $v;
			$this->modifiedColumns[] = Tbrh067GrupoNominaPeer::COD_GRUPO_NOMINA;
		}

		return $this;
	} // setCodGrupoNomina()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_grupo_nomina = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->tx_grupo_nomina = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->co_tp_nomina = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->cod_grupo_nomina = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = Tbrh067GrupoNominaPeer::NUM_COLUMNS - Tbrh067GrupoNominaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Tbrh067GrupoNomina object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Tbrh067GrupoNominaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = Tbrh067GrupoNominaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collTbrh070PrimaAntiguedads = null;
			$this->lastTbrh070PrimaAntiguedadCriteria = null;

			$this->collTbrh098ConceptoTiempos = null;
			$this->lastTbrh098ConceptoTiempoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTbrh067GrupoNomina:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Tbrh067GrupoNominaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			Tbrh067GrupoNominaPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseTbrh067GrupoNomina:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTbrh067GrupoNomina:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Tbrh067GrupoNominaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseTbrh067GrupoNomina:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			Tbrh067GrupoNominaPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = Tbrh067GrupoNominaPeer::CO_GRUPO_NOMINA;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = Tbrh067GrupoNominaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoGrupoNomina($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += Tbrh067GrupoNominaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTbrh070PrimaAntiguedads !== null) {
				foreach ($this->collTbrh070PrimaAntiguedads as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTbrh098ConceptoTiempos !== null) {
				foreach ($this->collTbrh098ConceptoTiempos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = Tbrh067GrupoNominaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTbrh070PrimaAntiguedads !== null) {
					foreach ($this->collTbrh070PrimaAntiguedads as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTbrh098ConceptoTiempos !== null) {
					foreach ($this->collTbrh098ConceptoTiempos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Tbrh067GrupoNominaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoGrupoNomina();
				break;
			case 1:
				return $this->getTxGrupoNomina();
				break;
			case 2:
				return $this->getCoTpNomina();
				break;
			case 3:
				return $this->getCodGrupoNomina();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = Tbrh067GrupoNominaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoGrupoNomina(),
			$keys[1] => $this->getTxGrupoNomina(),
			$keys[2] => $this->getCoTpNomina(),
			$keys[3] => $this->getCodGrupoNomina(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Tbrh067GrupoNominaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoGrupoNomina($value);
				break;
			case 1:
				$this->setTxGrupoNomina($value);
				break;
			case 2:
				$this->setCoTpNomina($value);
				break;
			case 3:
				$this->setCodGrupoNomina($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = Tbrh067GrupoNominaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoGrupoNomina($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTxGrupoNomina($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCoTpNomina($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCodGrupoNomina($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(Tbrh067GrupoNominaPeer::DATABASE_NAME);

		if ($this->isColumnModified(Tbrh067GrupoNominaPeer::CO_GRUPO_NOMINA)) $criteria->add(Tbrh067GrupoNominaPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);
		if ($this->isColumnModified(Tbrh067GrupoNominaPeer::TX_GRUPO_NOMINA)) $criteria->add(Tbrh067GrupoNominaPeer::TX_GRUPO_NOMINA, $this->tx_grupo_nomina);
		if ($this->isColumnModified(Tbrh067GrupoNominaPeer::CO_TP_NOMINA)) $criteria->add(Tbrh067GrupoNominaPeer::CO_TP_NOMINA, $this->co_tp_nomina);
		if ($this->isColumnModified(Tbrh067GrupoNominaPeer::COD_GRUPO_NOMINA)) $criteria->add(Tbrh067GrupoNominaPeer::COD_GRUPO_NOMINA, $this->cod_grupo_nomina);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(Tbrh067GrupoNominaPeer::DATABASE_NAME);

		$criteria->add(Tbrh067GrupoNominaPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoGrupoNomina();
	}

	/**
	 * Generic method to set the primary key (co_grupo_nomina column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoGrupoNomina($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Tbrh067GrupoNomina (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTxGrupoNomina($this->tx_grupo_nomina);

		$copyObj->setCoTpNomina($this->co_tp_nomina);

		$copyObj->setCodGrupoNomina($this->cod_grupo_nomina);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTbrh070PrimaAntiguedads() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTbrh070PrimaAntiguedad($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTbrh098ConceptoTiempos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTbrh098ConceptoTiempo($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setCoGrupoNomina(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Tbrh067GrupoNomina Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     Tbrh067GrupoNominaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new Tbrh067GrupoNominaPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collTbrh070PrimaAntiguedads collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTbrh070PrimaAntiguedads()
	 */
	public function clearTbrh070PrimaAntiguedads()
	{
		$this->collTbrh070PrimaAntiguedads = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTbrh070PrimaAntiguedads collection (array).
	 *
	 * By default this just sets the collTbrh070PrimaAntiguedads collection to an empty array (like clearcollTbrh070PrimaAntiguedads());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTbrh070PrimaAntiguedads()
	{
		$this->collTbrh070PrimaAntiguedads = array();
	}

	/**
	 * Gets an array of Tbrh070PrimaAntiguedad objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tbrh067GrupoNomina has previously been saved, it will retrieve
	 * related Tbrh070PrimaAntiguedads from storage. If this Tbrh067GrupoNomina is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tbrh070PrimaAntiguedad[]
	 * @throws     PropelException
	 */
	public function getTbrh070PrimaAntiguedads($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Tbrh067GrupoNominaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbrh070PrimaAntiguedads === null) {
			if ($this->isNew()) {
			   $this->collTbrh070PrimaAntiguedads = array();
			} else {

				$criteria->add(Tbrh070PrimaAntiguedadPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				Tbrh070PrimaAntiguedadPeer::addSelectColumns($criteria);
				$this->collTbrh070PrimaAntiguedads = Tbrh070PrimaAntiguedadPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(Tbrh070PrimaAntiguedadPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				Tbrh070PrimaAntiguedadPeer::addSelectColumns($criteria);
				if (!isset($this->lastTbrh070PrimaAntiguedadCriteria) || !$this->lastTbrh070PrimaAntiguedadCriteria->equals($criteria)) {
					$this->collTbrh070PrimaAntiguedads = Tbrh070PrimaAntiguedadPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTbrh070PrimaAntiguedadCriteria = $criteria;
		return $this->collTbrh070PrimaAntiguedads;
	}

	/**
	 * Returns the number of related Tbrh070PrimaAntiguedad objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tbrh070PrimaAntiguedad objects.
	 * @throws     PropelException
	 */
	public function countTbrh070PrimaAntiguedads(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Tbrh067GrupoNominaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTbrh070PrimaAntiguedads === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(Tbrh070PrimaAntiguedadPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				$count = Tbrh070PrimaAntiguedadPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(Tbrh070PrimaAntiguedadPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				if (!isset($this->lastTbrh070PrimaAntiguedadCriteria) || !$this->lastTbrh070PrimaAntiguedadCriteria->equals($criteria)) {
					$count = Tbrh070PrimaAntiguedadPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collTbrh070PrimaAntiguedads);
				}
			} else {
				$count = count($this->collTbrh070PrimaAntiguedads);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tbrh070PrimaAntiguedad object to this object
	 * through the Tbrh070PrimaAntiguedad foreign key attribute.
	 *
	 * @param      Tbrh070PrimaAntiguedad $l Tbrh070PrimaAntiguedad
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTbrh070PrimaAntiguedad(Tbrh070PrimaAntiguedad $l)
	{
		if ($this->collTbrh070PrimaAntiguedads === null) {
			$this->initTbrh070PrimaAntiguedads();
		}
		if (!in_array($l, $this->collTbrh070PrimaAntiguedads, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTbrh070PrimaAntiguedads, $l);
			$l->setTbrh067GrupoNomina($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbrh067GrupoNomina is new, it will return
	 * an empty collection; or if this Tbrh067GrupoNomina has previously
	 * been saved, it will retrieve related Tbrh070PrimaAntiguedads from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbrh067GrupoNomina.
	 */
	public function getTbrh070PrimaAntiguedadsJoinTbrh017TpNomina($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Tbrh067GrupoNominaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbrh070PrimaAntiguedads === null) {
			if ($this->isNew()) {
				$this->collTbrh070PrimaAntiguedads = array();
			} else {

				$criteria->add(Tbrh070PrimaAntiguedadPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				$this->collTbrh070PrimaAntiguedads = Tbrh070PrimaAntiguedadPeer::doSelectJoinTbrh017TpNomina($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(Tbrh070PrimaAntiguedadPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

			if (!isset($this->lastTbrh070PrimaAntiguedadCriteria) || !$this->lastTbrh070PrimaAntiguedadCriteria->equals($criteria)) {
				$this->collTbrh070PrimaAntiguedads = Tbrh070PrimaAntiguedadPeer::doSelectJoinTbrh017TpNomina($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbrh070PrimaAntiguedadCriteria = $criteria;

		return $this->collTbrh070PrimaAntiguedads;
	}

	/**
	 * Clears out the collTbrh098ConceptoTiempos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTbrh098ConceptoTiempos()
	 */
	public function clearTbrh098ConceptoTiempos()
	{
		$this->collTbrh098ConceptoTiempos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTbrh098ConceptoTiempos collection (array).
	 *
	 * By default this just sets the collTbrh098ConceptoTiempos collection to an empty array (like clearcollTbrh098ConceptoTiempos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTbrh098ConceptoTiempos()
	{
		$this->collTbrh098ConceptoTiempos = array();
	}

	/**
	 * Gets an array of Tbrh098ConceptoTiempo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tbrh067GrupoNomina has previously been saved, it will retrieve
	 * related Tbrh098ConceptoTiempos from storage. If this Tbrh067GrupoNomina is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tbrh098ConceptoTiempo[]
	 * @throws     PropelException
	 */
	public function getTbrh098ConceptoTiempos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Tbrh067GrupoNominaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbrh098ConceptoTiempos === null) {
			if ($this->isNew()) {
			   $this->collTbrh098ConceptoTiempos = array();
			} else {

				$criteria->add(Tbrh098ConceptoTiempoPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				Tbrh098ConceptoTiempoPeer::addSelectColumns($criteria);
				$this->collTbrh098ConceptoTiempos = Tbrh098ConceptoTiempoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(Tbrh098ConceptoTiempoPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				Tbrh098ConceptoTiempoPeer::addSelectColumns($criteria);
				if (!isset($this->lastTbrh098ConceptoTiempoCriteria) || !$this->lastTbrh098ConceptoTiempoCriteria->equals($criteria)) {
					$this->collTbrh098ConceptoTiempos = Tbrh098ConceptoTiempoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTbrh098ConceptoTiempoCriteria = $criteria;
		return $this->collTbrh098ConceptoTiempos;
	}

	/**
	 * Returns the number of related Tbrh098ConceptoTiempo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tbrh098ConceptoTiempo objects.
	 * @throws     PropelException
	 */
	public function countTbrh098ConceptoTiempos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Tbrh067GrupoNominaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTbrh098ConceptoTiempos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(Tbrh098ConceptoTiempoPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				$count = Tbrh098ConceptoTiempoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(Tbrh098ConceptoTiempoPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				if (!isset($this->lastTbrh098ConceptoTiempoCriteria) || !$this->lastTbrh098ConceptoTiempoCriteria->equals($criteria)) {
					$count = Tbrh098ConceptoTiempoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collTbrh098ConceptoTiempos);
				}
			} else {
				$count = count($this->collTbrh098ConceptoTiempos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tbrh098ConceptoTiempo object to this object
	 * through the Tbrh098ConceptoTiempo foreign key attribute.
	 *
	 * @param      Tbrh098ConceptoTiempo $l Tbrh098ConceptoTiempo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTbrh098ConceptoTiempo(Tbrh098ConceptoTiempo $l)
	{
		if ($this->collTbrh098ConceptoTiempos === null) {
			$this->initTbrh098ConceptoTiempos();
		}
		if (!in_array($l, $this->collTbrh098ConceptoTiempos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTbrh098ConceptoTiempos, $l);
			$l->setTbrh067GrupoNomina($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbrh067GrupoNomina is new, it will return
	 * an empty collection; or if this Tbrh067GrupoNomina has previously
	 * been saved, it will retrieve related Tbrh098ConceptoTiempos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbrh067GrupoNomina.
	 */
	public function getTbrh098ConceptoTiemposJoinTbrh017TpNomina($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Tbrh067GrupoNominaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbrh098ConceptoTiempos === null) {
			if ($this->isNew()) {
				$this->collTbrh098ConceptoTiempos = array();
			} else {

				$criteria->add(Tbrh098ConceptoTiempoPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				$this->collTbrh098ConceptoTiempos = Tbrh098ConceptoTiempoPeer::doSelectJoinTbrh017TpNomina($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(Tbrh098ConceptoTiempoPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

			if (!isset($this->lastTbrh098ConceptoTiempoCriteria) || !$this->lastTbrh098ConceptoTiempoCriteria->equals($criteria)) {
				$this->collTbrh098ConceptoTiempos = Tbrh098ConceptoTiempoPeer::doSelectJoinTbrh017TpNomina($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbrh098ConceptoTiempoCriteria = $criteria;

		return $this->collTbrh098ConceptoTiempos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbrh067GrupoNomina is new, it will return
	 * an empty collection; or if this Tbrh067GrupoNomina has previously
	 * been saved, it will retrieve related Tbrh098ConceptoTiempos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbrh067GrupoNomina.
	 */
	public function getTbrh098ConceptoTiemposJoinTbrh014Concepto($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(Tbrh067GrupoNominaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbrh098ConceptoTiempos === null) {
			if ($this->isNew()) {
				$this->collTbrh098ConceptoTiempos = array();
			} else {

				$criteria->add(Tbrh098ConceptoTiempoPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

				$this->collTbrh098ConceptoTiempos = Tbrh098ConceptoTiempoPeer::doSelectJoinTbrh014Concepto($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(Tbrh098ConceptoTiempoPeer::CO_GRUPO_NOMINA, $this->co_grupo_nomina);

			if (!isset($this->lastTbrh098ConceptoTiempoCriteria) || !$this->lastTbrh098ConceptoTiempoCriteria->equals($criteria)) {
				$this->collTbrh098ConceptoTiempos = Tbrh098ConceptoTiempoPeer::doSelectJoinTbrh014Concepto($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbrh098ConceptoTiempoCriteria = $criteria;

		return $this->collTbrh098ConceptoTiempos;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTbrh070PrimaAntiguedads) {
				foreach ((array) $this->collTbrh070PrimaAntiguedads as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTbrh098ConceptoTiempos) {
				foreach ((array) $this->collTbrh098ConceptoTiempos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTbrh070PrimaAntiguedads = null;
		$this->collTbrh098ConceptoTiempos = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseTbrh067GrupoNomina:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseTbrh067GrupoNomina::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseTbrh067GrupoNomina
