<?php

/**
 * Base static class for performing query and update operations on the 'tb097_modificacion_detalle' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun  6 08:13:30 2022
 *
 * @package    lib.model.om
 */
abstract class BaseTb097ModificacionDetallePeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'tb097_modificacion_detalle';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Tb097ModificacionDetalle';

	/** The total number of columns. */
	const NUM_COLUMNS = 21;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'tb097_modificacion_detalle.ID';

	/** the column name for the ID_TB096_PRESUPUESTO_MODIFICACION field */
	const ID_TB096_PRESUPUESTO_MODIFICACION = 'tb097_modificacion_detalle.ID_TB096_PRESUPUESTO_MODIFICACION';

	/** the column name for the ID_TB013_ANIO_FISCAL field */
	const ID_TB013_ANIO_FISCAL = 'tb097_modificacion_detalle.ID_TB013_ANIO_FISCAL';

	/** the column name for the ID_TB083_PROYECTO_AC field */
	const ID_TB083_PROYECTO_AC = 'tb097_modificacion_detalle.ID_TB083_PROYECTO_AC';

	/** the column name for the ID_TB084_ACCION_ESPECIFICA field */
	const ID_TB084_ACCION_ESPECIFICA = 'tb097_modificacion_detalle.ID_TB084_ACCION_ESPECIFICA';

	/** the column name for the ID_TB085_PRESUPUESTO field */
	const ID_TB085_PRESUPUESTO = 'tb097_modificacion_detalle.ID_TB085_PRESUPUESTO';

	/** the column name for the NU_PARTIDA field */
	const NU_PARTIDA = 'tb097_modificacion_detalle.NU_PARTIDA';

	/** the column name for the ID_TB098_TIPO_DISTRIBUCION field */
	const ID_TB098_TIPO_DISTRIBUCION = 'tb097_modificacion_detalle.ID_TB098_TIPO_DISTRIBUCION';

	/** the column name for the MO_DISTRIBUCION field */
	const MO_DISTRIBUCION = 'tb097_modificacion_detalle.MO_DISTRIBUCION';

	/** the column name for the IN_ACTIVO field */
	const IN_ACTIVO = 'tb097_modificacion_detalle.IN_ACTIVO';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'tb097_modificacion_detalle.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'tb097_modificacion_detalle.UPDATED_AT';

	/** the column name for the ID_TB064_PRESUPUESTO_INGRESO field */
	const ID_TB064_PRESUPUESTO_INGRESO = 'tb097_modificacion_detalle.ID_TB064_PRESUPUESTO_INGRESO';

	/** the column name for the ID_TB082_EJECUTOR_ORIGEN field */
	const ID_TB082_EJECUTOR_ORIGEN = 'tb097_modificacion_detalle.ID_TB082_EJECUTOR_ORIGEN';

	/** the column name for the ID_TB082_EJECUTOR_DESTINO field */
	const ID_TB082_EJECUTOR_DESTINO = 'tb097_modificacion_detalle.ID_TB082_EJECUTOR_DESTINO';

	/** the column name for the IN_TRASPASO field */
	const IN_TRASPASO = 'tb097_modificacion_detalle.IN_TRASPASO';

	/** the column name for the ID_TB139_APLICACION field */
	const ID_TB139_APLICACION = 'tb097_modificacion_detalle.ID_TB139_APLICACION';

	/** the column name for the NU_APLICACION field */
	const NU_APLICACION = 'tb097_modificacion_detalle.NU_APLICACION';

	/** the column name for the MO_DISPONIBLE field */
	const MO_DISPONIBLE = 'tb097_modificacion_detalle.MO_DISPONIBLE';

	/** the column name for the CO_SOLICITUD_ANULAR field */
	const CO_SOLICITUD_ANULAR = 'tb097_modificacion_detalle.CO_SOLICITUD_ANULAR';

	/** the column name for the IN_ANULAR field */
	const IN_ANULAR = 'tb097_modificacion_detalle.IN_ANULAR';

	/**
	 * An identiy map to hold any loaded instances of Tb097ModificacionDetalle objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Tb097ModificacionDetalle[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'IdTb096PresupuestoModificacion', 'IdTb013AnioFiscal', 'IdTb083ProyectoAc', 'IdTb084AccionEspecifica', 'IdTb085Presupuesto', 'NuPartida', 'IdTb098TipoDistribucion', 'MoDistribucion', 'InActivo', 'CreatedAt', 'UpdatedAt', 'IdTb064PresupuestoIngreso', 'IdTb082EjecutorOrigen', 'IdTb082EjecutorDestino', 'InTraspaso', 'IdTb139Aplicacion', 'NuAplicacion', 'MoDisponible', 'CoSolicitudAnular', 'InAnular', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'idTb096PresupuestoModificacion', 'idTb013AnioFiscal', 'idTb083ProyectoAc', 'idTb084AccionEspecifica', 'idTb085Presupuesto', 'nuPartida', 'idTb098TipoDistribucion', 'moDistribucion', 'inActivo', 'createdAt', 'updatedAt', 'idTb064PresupuestoIngreso', 'idTb082EjecutorOrigen', 'idTb082EjecutorDestino', 'inTraspaso', 'idTb139Aplicacion', 'nuAplicacion', 'moDisponible', 'coSolicitudAnular', 'inAnular', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::ID_TB096_PRESUPUESTO_MODIFICACION, self::ID_TB013_ANIO_FISCAL, self::ID_TB083_PROYECTO_AC, self::ID_TB084_ACCION_ESPECIFICA, self::ID_TB085_PRESUPUESTO, self::NU_PARTIDA, self::ID_TB098_TIPO_DISTRIBUCION, self::MO_DISTRIBUCION, self::IN_ACTIVO, self::CREATED_AT, self::UPDATED_AT, self::ID_TB064_PRESUPUESTO_INGRESO, self::ID_TB082_EJECUTOR_ORIGEN, self::ID_TB082_EJECUTOR_DESTINO, self::IN_TRASPASO, self::ID_TB139_APLICACION, self::NU_APLICACION, self::MO_DISPONIBLE, self::CO_SOLICITUD_ANULAR, self::IN_ANULAR, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'id_tb096_presupuesto_modificacion', 'id_tb013_anio_fiscal', 'id_tb083_proyecto_ac', 'id_tb084_accion_especifica', 'id_tb085_presupuesto', 'nu_partida', 'id_tb098_tipo_distribucion', 'mo_distribucion', 'in_activo', 'created_at', 'updated_at', 'id_tb064_presupuesto_ingreso', 'id_tb082_ejecutor_origen', 'id_tb082_ejecutor_destino', 'in_traspaso', 'id_tb139_aplicacion', 'nu_aplicacion', 'mo_disponible', 'co_solicitud_anular', 'in_anular', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'IdTb096PresupuestoModificacion' => 1, 'IdTb013AnioFiscal' => 2, 'IdTb083ProyectoAc' => 3, 'IdTb084AccionEspecifica' => 4, 'IdTb085Presupuesto' => 5, 'NuPartida' => 6, 'IdTb098TipoDistribucion' => 7, 'MoDistribucion' => 8, 'InActivo' => 9, 'CreatedAt' => 10, 'UpdatedAt' => 11, 'IdTb064PresupuestoIngreso' => 12, 'IdTb082EjecutorOrigen' => 13, 'IdTb082EjecutorDestino' => 14, 'InTraspaso' => 15, 'IdTb139Aplicacion' => 16, 'NuAplicacion' => 17, 'MoDisponible' => 18, 'CoSolicitudAnular' => 19, 'InAnular' => 20, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'idTb096PresupuestoModificacion' => 1, 'idTb013AnioFiscal' => 2, 'idTb083ProyectoAc' => 3, 'idTb084AccionEspecifica' => 4, 'idTb085Presupuesto' => 5, 'nuPartida' => 6, 'idTb098TipoDistribucion' => 7, 'moDistribucion' => 8, 'inActivo' => 9, 'createdAt' => 10, 'updatedAt' => 11, 'idTb064PresupuestoIngreso' => 12, 'idTb082EjecutorOrigen' => 13, 'idTb082EjecutorDestino' => 14, 'inTraspaso' => 15, 'idTb139Aplicacion' => 16, 'nuAplicacion' => 17, 'moDisponible' => 18, 'coSolicitudAnular' => 19, 'inAnular' => 20, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::ID_TB096_PRESUPUESTO_MODIFICACION => 1, self::ID_TB013_ANIO_FISCAL => 2, self::ID_TB083_PROYECTO_AC => 3, self::ID_TB084_ACCION_ESPECIFICA => 4, self::ID_TB085_PRESUPUESTO => 5, self::NU_PARTIDA => 6, self::ID_TB098_TIPO_DISTRIBUCION => 7, self::MO_DISTRIBUCION => 8, self::IN_ACTIVO => 9, self::CREATED_AT => 10, self::UPDATED_AT => 11, self::ID_TB064_PRESUPUESTO_INGRESO => 12, self::ID_TB082_EJECUTOR_ORIGEN => 13, self::ID_TB082_EJECUTOR_DESTINO => 14, self::IN_TRASPASO => 15, self::ID_TB139_APLICACION => 16, self::NU_APLICACION => 17, self::MO_DISPONIBLE => 18, self::CO_SOLICITUD_ANULAR => 19, self::IN_ANULAR => 20, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'id_tb096_presupuesto_modificacion' => 1, 'id_tb013_anio_fiscal' => 2, 'id_tb083_proyecto_ac' => 3, 'id_tb084_accion_especifica' => 4, 'id_tb085_presupuesto' => 5, 'nu_partida' => 6, 'id_tb098_tipo_distribucion' => 7, 'mo_distribucion' => 8, 'in_activo' => 9, 'created_at' => 10, 'updated_at' => 11, 'id_tb064_presupuesto_ingreso' => 12, 'id_tb082_ejecutor_origen' => 13, 'id_tb082_ejecutor_destino' => 14, 'in_traspaso' => 15, 'id_tb139_aplicacion' => 16, 'nu_aplicacion' => 17, 'mo_disponible' => 18, 'co_solicitud_anular' => 19, 'in_anular' => 20, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new Tb097ModificacionDetalleMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. Tb097ModificacionDetallePeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(Tb097ModificacionDetallePeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB096_PRESUPUESTO_MODIFICACION);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB013_ANIO_FISCAL);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB083_PROYECTO_AC);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB084_ACCION_ESPECIFICA);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB085_PRESUPUESTO);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::NU_PARTIDA);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB098_TIPO_DISTRIBUCION);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::MO_DISTRIBUCION);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::IN_ACTIVO);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::CREATED_AT);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::UPDATED_AT);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB064_PRESUPUESTO_INGRESO);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB082_EJECUTOR_ORIGEN);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB082_EJECUTOR_DESTINO);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::IN_TRASPASO);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::ID_TB139_APLICACION);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::NU_APLICACION);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::MO_DISPONIBLE);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::CO_SOLICITUD_ANULAR);

		$criteria->addSelectColumn(Tb097ModificacionDetallePeer::IN_ANULAR);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb097ModificacionDetallePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb097ModificacionDetallePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Tb097ModificacionDetalle
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = Tb097ModificacionDetallePeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return Tb097ModificacionDetallePeer::populateObjects(Tb097ModificacionDetallePeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			Tb097ModificacionDetallePeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Tb097ModificacionDetalle $value A Tb097ModificacionDetalle object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Tb097ModificacionDetalle $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Tb097ModificacionDetalle object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Tb097ModificacionDetalle) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Tb097ModificacionDetalle object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Tb097ModificacionDetalle Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = Tb097ModificacionDetallePeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = Tb097ModificacionDetallePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = Tb097ModificacionDetallePeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				Tb097ModificacionDetallePeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Tb096PresupuestoModificacion table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb096PresupuestoModificacion(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb097ModificacionDetallePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb097ModificacionDetallePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB096_PRESUPUESTO_MODIFICACION,), array(Tb096PresupuestoModificacionPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb084AccionEspecifica table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb084AccionEspecifica(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb097ModificacionDetallePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb097ModificacionDetallePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB084_ACCION_ESPECIFICA,), array(Tb084AccionEspecificaPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb085Presupuesto table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTb085Presupuesto(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb097ModificacionDetallePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb097ModificacionDetallePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB085_PRESUPUESTO,), array(Tb085PresupuestoPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Tb097ModificacionDetalle objects pre-filled with their Tb096PresupuestoModificacion objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb097ModificacionDetalle objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb096PresupuestoModificacion(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb097ModificacionDetallePeer::addSelectColumns($c);
		$startcol = (Tb097ModificacionDetallePeer::NUM_COLUMNS - Tb097ModificacionDetallePeer::NUM_LAZY_LOAD_COLUMNS);
		Tb096PresupuestoModificacionPeer::addSelectColumns($c);

		$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB096_PRESUPUESTO_MODIFICACION,), array(Tb096PresupuestoModificacionPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb097ModificacionDetallePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb097ModificacionDetallePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb097ModificacionDetallePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb097ModificacionDetallePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb096PresupuestoModificacionPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb096PresupuestoModificacionPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb096PresupuestoModificacionPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb096PresupuestoModificacionPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to $obj2 (Tb096PresupuestoModificacion)
				$obj2->addTb097ModificacionDetalle($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb097ModificacionDetalle objects pre-filled with their Tb084AccionEspecifica objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb097ModificacionDetalle objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb084AccionEspecifica(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb097ModificacionDetallePeer::addSelectColumns($c);
		$startcol = (Tb097ModificacionDetallePeer::NUM_COLUMNS - Tb097ModificacionDetallePeer::NUM_LAZY_LOAD_COLUMNS);
		Tb084AccionEspecificaPeer::addSelectColumns($c);

		$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB084_ACCION_ESPECIFICA,), array(Tb084AccionEspecificaPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb097ModificacionDetallePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb097ModificacionDetallePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb097ModificacionDetallePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb097ModificacionDetallePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb084AccionEspecificaPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb084AccionEspecificaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb084AccionEspecificaPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb084AccionEspecificaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to $obj2 (Tb084AccionEspecifica)
				$obj2->addTb097ModificacionDetalle($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb097ModificacionDetalle objects pre-filled with their Tb085Presupuesto objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb097ModificacionDetalle objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTb085Presupuesto(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb097ModificacionDetallePeer::addSelectColumns($c);
		$startcol = (Tb097ModificacionDetallePeer::NUM_COLUMNS - Tb097ModificacionDetallePeer::NUM_LAZY_LOAD_COLUMNS);
		Tb085PresupuestoPeer::addSelectColumns($c);

		$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB085_PRESUPUESTO,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb097ModificacionDetallePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb097ModificacionDetallePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = Tb097ModificacionDetallePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb097ModificacionDetallePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = Tb085PresupuestoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb085PresupuestoPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					Tb085PresupuestoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to $obj2 (Tb085Presupuesto)
				$obj2->addTb097ModificacionDetalle($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(Tb097ModificacionDetallePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb097ModificacionDetallePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB096_PRESUPUESTO_MODIFICACION,), array(Tb096PresupuestoModificacionPeer::ID,), $join_behavior);
		$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB084_ACCION_ESPECIFICA,), array(Tb084AccionEspecificaPeer::ID,), $join_behavior);
		$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB085_PRESUPUESTO,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Tb097ModificacionDetalle objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb097ModificacionDetalle objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb097ModificacionDetallePeer::addSelectColumns($c);
		$startcol2 = (Tb097ModificacionDetallePeer::NUM_COLUMNS - Tb097ModificacionDetallePeer::NUM_LAZY_LOAD_COLUMNS);

		Tb096PresupuestoModificacionPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb096PresupuestoModificacionPeer::NUM_COLUMNS - Tb096PresupuestoModificacionPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb084AccionEspecificaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb084AccionEspecificaPeer::NUM_COLUMNS - Tb084AccionEspecificaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB096_PRESUPUESTO_MODIFICACION,), array(Tb096PresupuestoModificacionPeer::ID,), $join_behavior);
		$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB084_ACCION_ESPECIFICA,), array(Tb084AccionEspecificaPeer::ID,), $join_behavior);
		$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB085_PRESUPUESTO,), array(Tb085PresupuestoPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb097ModificacionDetallePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb097ModificacionDetallePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb097ModificacionDetallePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb097ModificacionDetallePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Tb096PresupuestoModificacion rows

			$key2 = Tb096PresupuestoModificacionPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = Tb096PresupuestoModificacionPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = Tb096PresupuestoModificacionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb096PresupuestoModificacionPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to the collection in $obj2 (Tb096PresupuestoModificacion)
				$obj2->addTb097ModificacionDetalle($obj1);
			} // if joined row not null

			// Add objects for joined Tb084AccionEspecifica rows

			$key3 = Tb084AccionEspecificaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = Tb084AccionEspecificaPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = Tb084AccionEspecificaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb084AccionEspecificaPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to the collection in $obj3 (Tb084AccionEspecifica)
				$obj3->addTb097ModificacionDetalle($obj1);
			} // if joined row not null

			// Add objects for joined Tb085Presupuesto rows

			$key4 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = Tb085PresupuestoPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					Tb085PresupuestoPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to the collection in $obj4 (Tb085Presupuesto)
				$obj4->addTb097ModificacionDetalle($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb096PresupuestoModificacion table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb096PresupuestoModificacion(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb097ModificacionDetallePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB084_ACCION_ESPECIFICA,), array(Tb084AccionEspecificaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB085_PRESUPUESTO,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb084AccionEspecifica table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb084AccionEspecifica(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb097ModificacionDetallePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB096_PRESUPUESTO_MODIFICACION,), array(Tb096PresupuestoModificacionPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB085_PRESUPUESTO,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Tb085Presupuesto table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTb085Presupuesto(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			Tb097ModificacionDetallePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB096_PRESUPUESTO_MODIFICACION,), array(Tb096PresupuestoModificacionPeer::ID,), $join_behavior);
				$criteria->addJoin(array(Tb097ModificacionDetallePeer::ID_TB084_ACCION_ESPECIFICA,), array(Tb084AccionEspecificaPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Tb097ModificacionDetalle objects pre-filled with all related objects except Tb096PresupuestoModificacion.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb097ModificacionDetalle objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb096PresupuestoModificacion(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb097ModificacionDetallePeer::addSelectColumns($c);
		$startcol2 = (Tb097ModificacionDetallePeer::NUM_COLUMNS - Tb097ModificacionDetallePeer::NUM_LAZY_LOAD_COLUMNS);

		Tb084AccionEspecificaPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb084AccionEspecificaPeer::NUM_COLUMNS - Tb084AccionEspecificaPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB084_ACCION_ESPECIFICA,), array(Tb084AccionEspecificaPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB085_PRESUPUESTO,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb097ModificacionDetallePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb097ModificacionDetallePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb097ModificacionDetallePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb097ModificacionDetallePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb084AccionEspecifica rows

				$key2 = Tb084AccionEspecificaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb084AccionEspecificaPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb084AccionEspecificaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb084AccionEspecificaPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to the collection in $obj2 (Tb084AccionEspecifica)
				$obj2->addTb097ModificacionDetalle($obj1);

			} // if joined row is not null

				// Add objects for joined Tb085Presupuesto rows

				$key3 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = Tb085PresupuestoPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb085PresupuestoPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to the collection in $obj3 (Tb085Presupuesto)
				$obj3->addTb097ModificacionDetalle($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb097ModificacionDetalle objects pre-filled with all related objects except Tb084AccionEspecifica.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb097ModificacionDetalle objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb084AccionEspecifica(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb097ModificacionDetallePeer::addSelectColumns($c);
		$startcol2 = (Tb097ModificacionDetallePeer::NUM_COLUMNS - Tb097ModificacionDetallePeer::NUM_LAZY_LOAD_COLUMNS);

		Tb096PresupuestoModificacionPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb096PresupuestoModificacionPeer::NUM_COLUMNS - Tb096PresupuestoModificacionPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb085PresupuestoPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb085PresupuestoPeer::NUM_COLUMNS - Tb085PresupuestoPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB096_PRESUPUESTO_MODIFICACION,), array(Tb096PresupuestoModificacionPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB085_PRESUPUESTO,), array(Tb085PresupuestoPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb097ModificacionDetallePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb097ModificacionDetallePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb097ModificacionDetallePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb097ModificacionDetallePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb096PresupuestoModificacion rows

				$key2 = Tb096PresupuestoModificacionPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb096PresupuestoModificacionPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb096PresupuestoModificacionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb096PresupuestoModificacionPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to the collection in $obj2 (Tb096PresupuestoModificacion)
				$obj2->addTb097ModificacionDetalle($obj1);

			} // if joined row is not null

				// Add objects for joined Tb085Presupuesto rows

				$key3 = Tb085PresupuestoPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = Tb085PresupuestoPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = Tb085PresupuestoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb085PresupuestoPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to the collection in $obj3 (Tb085Presupuesto)
				$obj3->addTb097ModificacionDetalle($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tb097ModificacionDetalle objects pre-filled with all related objects except Tb085Presupuesto.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tb097ModificacionDetalle objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTb085Presupuesto(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		Tb097ModificacionDetallePeer::addSelectColumns($c);
		$startcol2 = (Tb097ModificacionDetallePeer::NUM_COLUMNS - Tb097ModificacionDetallePeer::NUM_LAZY_LOAD_COLUMNS);

		Tb096PresupuestoModificacionPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (Tb096PresupuestoModificacionPeer::NUM_COLUMNS - Tb096PresupuestoModificacionPeer::NUM_LAZY_LOAD_COLUMNS);

		Tb084AccionEspecificaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (Tb084AccionEspecificaPeer::NUM_COLUMNS - Tb084AccionEspecificaPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB096_PRESUPUESTO_MODIFICACION,), array(Tb096PresupuestoModificacionPeer::ID,), $join_behavior);
				$c->addJoin(array(Tb097ModificacionDetallePeer::ID_TB084_ACCION_ESPECIFICA,), array(Tb084AccionEspecificaPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = Tb097ModificacionDetallePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = Tb097ModificacionDetallePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = Tb097ModificacionDetallePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				Tb097ModificacionDetallePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Tb096PresupuestoModificacion rows

				$key2 = Tb096PresupuestoModificacionPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = Tb096PresupuestoModificacionPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = Tb096PresupuestoModificacionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					Tb096PresupuestoModificacionPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to the collection in $obj2 (Tb096PresupuestoModificacion)
				$obj2->addTb097ModificacionDetalle($obj1);

			} // if joined row is not null

				// Add objects for joined Tb084AccionEspecifica rows

				$key3 = Tb084AccionEspecificaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = Tb084AccionEspecificaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = Tb084AccionEspecificaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					Tb084AccionEspecificaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tb097ModificacionDetalle) to the collection in $obj3 (Tb084AccionEspecifica)
				$obj3->addTb097ModificacionDetalle($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return Tb097ModificacionDetallePeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Tb097ModificacionDetalle or Criteria object.
	 *
	 * @param      mixed $values Criteria or Tb097ModificacionDetalle object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Tb097ModificacionDetalle object
		}

		if ($criteria->containsKey(Tb097ModificacionDetallePeer::ID) && $criteria->keyContainsValue(Tb097ModificacionDetallePeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.Tb097ModificacionDetallePeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Tb097ModificacionDetalle or Criteria object.
	 *
	 * @param      mixed $values Criteria or Tb097ModificacionDetalle object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(Tb097ModificacionDetallePeer::ID);
			$selectCriteria->add(Tb097ModificacionDetallePeer::ID, $criteria->remove(Tb097ModificacionDetallePeer::ID), $comparison);

		} else { // $values is Tb097ModificacionDetalle object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseTb097ModificacionDetallePeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseTb097ModificacionDetallePeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the tb097_modificacion_detalle table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(Tb097ModificacionDetallePeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Tb097ModificacionDetalle or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Tb097ModificacionDetalle object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			Tb097ModificacionDetallePeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Tb097ModificacionDetalle) {
			// invalidate the cache for this single object
			Tb097ModificacionDetallePeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(Tb097ModificacionDetallePeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				Tb097ModificacionDetallePeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Tb097ModificacionDetalle object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Tb097ModificacionDetalle $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Tb097ModificacionDetalle $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(Tb097ModificacionDetallePeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(Tb097ModificacionDetallePeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(Tb097ModificacionDetallePeer::DATABASE_NAME, Tb097ModificacionDetallePeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = Tb097ModificacionDetallePeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      string $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Tb097ModificacionDetalle
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = Tb097ModificacionDetallePeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(Tb097ModificacionDetallePeer::DATABASE_NAME);
		$criteria->add(Tb097ModificacionDetallePeer::ID, $pk);

		$v = Tb097ModificacionDetallePeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(Tb097ModificacionDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(Tb097ModificacionDetallePeer::DATABASE_NAME);
			$criteria->add(Tb097ModificacionDetallePeer::ID, $pks, Criteria::IN);
			$objs = Tb097ModificacionDetallePeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseTb097ModificacionDetallePeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the Tb097ModificacionDetallePeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the Tb097ModificacionDetallePeer class:
//
// Propel::getDatabaseMap(Tb097ModificacionDetallePeer::DATABASE_NAME)->addTableBuilder(Tb097ModificacionDetallePeer::TABLE_NAME, Tb097ModificacionDetallePeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseTb097ModificacionDetallePeer::DATABASE_NAME)->addTableBuilder(BaseTb097ModificacionDetallePeer::TABLE_NAME, BaseTb097ModificacionDetallePeer::getMapBuilder());

